# Generated by Django 4.2.16 on 2024-09-07 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Customer Name")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("Retailer", "Retailer"), ("Wholesaler", "Wholesaler"), ("Distributor", "Distributor")],
                        max_length=50,
                        verbose_name="Customer Type",
                    ),
                ),
                ("contact", models.CharField(max_length=100, verbose_name="Contact Information")),
                ("email", models.EmailField(max_length=254, verbose_name="Email Address")),
                ("billing_address", models.TextField(verbose_name="Billing Address")),
                ("shipping_address", models.TextField(verbose_name="Shipping Address")),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Credit Limit"),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Current Balance"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Update Time")),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Producer Name")),
                ("contact", models.CharField(max_length=100, verbose_name="Contact Information")),
                ("email", models.EmailField(max_length=254, verbose_name="Email Address")),
                ("address", models.TextField(verbose_name="Physical Address")),
                ("registration_number", models.CharField(max_length=100, unique=True, verbose_name="Registration Number")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Update Time")),
            ],
            options={
                "verbose_name": "Producer",
                "verbose_name_plural": "Producers",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Product Name")),
                ("description", models.TextField(verbose_name="Product Description")),
                ("sku", models.CharField(max_length=100, unique=True, verbose_name="Stock Keeping Unit (SKU)")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price")),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Cost Price")),
                ("stock", models.IntegerField(verbose_name="Stock Quantity")),
                ("reorder_level", models.IntegerField(default=10, verbose_name="Reorder Level")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active Status")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Update Time")),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="producer.producer", verbose_name="Producer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(verbose_name="Quantity Sold")),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Sale Price")),
                ("sale_date", models.DateTimeField(auto_now_add=True, verbose_name="Sale Date")),
                ("customer_name", models.CharField(blank=True, max_length=100, verbose_name="End-User Name")),
                (
                    "customer_contact",
                    models.CharField(blank=True, max_length=100, verbose_name="End-User Contact Information"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Update Time")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="producer.customer", verbose_name="Customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="producer.product", verbose_name="Product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(max_length=100, unique=True, verbose_name="Order Number")),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Order Status",
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True, verbose_name="Order Date")),
                ("delivery_date", models.DateTimeField(blank=True, null=True, verbose_name="Delivery Date")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Total Price")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")],
                        default="Pending",
                        max_length=50,
                        verbose_name="Payment Status",
                    ),
                ),
                ("payment_due_date", models.DateTimeField(blank=True, null=True, verbose_name="Payment Due Date")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Update Time")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="producer.customer", verbose_name="Customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="producer.product", verbose_name="Product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producer.producer", verbose_name="Producer"
            ),
        ),
    ]
