# Generated by Django 4.2.16 on 2024-09-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Payment Status",
            ),
        ),
    ]
