# Generated by Django 4.2.16 on 2024-09-10 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_marketplaceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='bid_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bid End Date'),
            preserve_default=False,
        ),
    ]
