# Generated by Django 4.2.16 on 2024-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_marketplaceproduct_bid_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceproduct',
            name='bid_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bid End Date'),
        ),
    ]
