# Generated by Django 4.2.16 on 2024-09-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_marketplaceproduct_bid_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='producer',
        ),
    ]
