# Generated by Django 4.2.16 on 2024-09-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0007_remove_customer_producer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.FileField(upload_to="product_images/")),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True, verbose_name="Alternative Text")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="producer.product"
                    ),
                ),
            ],
        ),
    ]
