# Generated by Django 4.2.16 on 2024-09-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0009_product_rate_alter_productimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rate",
        ),
    ]
