# Generated by Django 4.2.16 on 2024-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0010_remove_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='is_pushed_to_marketplace',
            field=models.BooleanField(default=False, verbose_name='Is Stock moved to marketplace'),
        ),
    ]
