# Generated by Django 4.2.16 on 2024-09-29 07:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0016_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Local Unit Location', null=True, srid=4326),
        ),
    ]
