# Generated by Django 4.2.16 on 2024-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0019_alter_producer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Physical Address'),
        ),
        migrations.AddField(
            model_name='producer',
            name='address_ne',
            field=models.TextField(null=True, verbose_name='Physical Address'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Producer Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_ne',
            field=models.CharField(max_length=100, null=True, verbose_name='Producer Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='registration_number_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='producer',
            name='registration_number_ne',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Registration Number'),
        ),
    ]
