# Generated by Django 4.2.16 on 2024-10-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0021_remove_productimage_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location of the product",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="producer.city",
                verbose_name="Location",
            ),
        ),
    ]
