# Generated by Django 4.2.23 on 2025-07-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0023_ledgerentry_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="avg_daily_demand",
            field=models.FloatField(
                default=0.0, help_text="Auto-computed from sales history", verbose_name="Average Daily Demand"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="lead_time_days",
            field=models.PositiveIntegerField(default=7, help_text="Supplier lead time", verbose_name="Lead Time (days)"),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_point",
            field=models.IntegerField(
                default=0, help_text="avg_daily_demand × lead_time + safety_stock", verbose_name="Reorder Point"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_quantity",
            field=models.IntegerField(
                default=0, help_text="Optimal order quantity Q*", verbose_name="Reorder Quantity (EOQ)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="safety_stock",
            field=models.IntegerField(default=0, help_text="z-factor × σ(Demand × LeadTime)", verbose_name="Safety Stock"),
        ),
        migrations.AddField(
            model_name="product",
            name="stddev_daily_demand",
            field=models.FloatField(
                default=0.0, help_text="Auto-computed from sales history", verbose_name="Daily Demand Std. Dev."
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                ("sent_to_vendor", models.BooleanField(default=False)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="producer.product")),
            ],
        ),
    ]
