# Generated by Django 4.2.23 on 2025-07-03 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0025_alter_purchaseorder_options_purchaseorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('quantity_in', models.PositiveIntegerField(default=0, verbose_name='Stock In')),
                ('quantity_out', models.PositiveIntegerField(default=0, verbose_name='Stock Out')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_histories', to='producer.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock Histories',
                'ordering': ['-date'],
            },
        ),
    ]
