# Generated by Django 4.2.23 on 2025-07-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0026_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='stock_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock After Movement'),
        ),
    ]
