# Generated by Django 4.2.23 on 2025-07-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0029_remove_marketplaceproduct_bid_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketplaceproduct",
            name="listed_price",
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="discounted_price",
            field=models.FloatField(
                blank=True, help_text="Discounted price if applicable.", null=True, verbose_name="Discounted Price"
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="estimated_delivery_days",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Estimated Delivery Days"),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="offer_end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Offer End"),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="offer_start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Offer Start"),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="recent_purchases_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Recent Purchases (24h)"),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Shipping Cost"),
        ),
        migrations.CreateModel(
            name="MarketplaceProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Variant Name")),
                ("value", models.CharField(max_length=100, verbose_name="Variant Value")),
                ("additional_price", models.FloatField(default=0, verbose_name="Additional Price")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="producer.marketplaceproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "unique_together": {("product", "name", "value")},
            },
        ),
        migrations.CreateModel(
            name="MarketplaceProductReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], verbose_name="Rating"
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True, verbose_name="Review")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="producer.marketplaceproduct"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
        migrations.CreateModel(
            name="MarketplaceBulkPriceTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_quantity", models.PositiveIntegerField(verbose_name="Min Quantity")),
                ("discount_percent", models.FloatField(blank=True, null=True, verbose_name="Discount Percent")),
                ("price_per_unit", models.FloatField(blank=True, null=True, verbose_name="Price Per Unit")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_price_tiers",
                        to="producer.marketplaceproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Price Tier",
                "verbose_name_plural": "Bulk Price Tiers",
                "ordering": ["min_quantity"],
                "unique_together": {("product", "min_quantity")},
            },
        ),
    ]
