# Generated by Django 4.2.23 on 2025-07-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0030_remove_marketplaceproduct_listed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='listed_price',
            field=models.FloatField(default=100, help_text='Original price before discount.', verbose_name='Listed Price'),
            preserve_default=False,
        ),
    ]
