# Generated by Django 4.2.23 on 2025-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0032_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="projected_stockout_date_field",
            field=models.DateField(blank=True, null=True, verbose_name="Projected Stockout Date"),
        ),
    ]
