# Generated by Django 4.2.23 on 2025-07-14 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0033_product_projected_stockout_date_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, help_text="Number of units sold", verbose_name="Quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit at the time of sale",
                        max_digits=10,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name="Total Amount"),
                ),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Sale Date")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Optional reference number or code",
                        max_length=100,
                        null=True,
                        verbose_name="Reference",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_sales",
                        to="producer.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="User"
                    ),
                ),
            ],
            options={
                "verbose_name": "Direct Sale",
                "verbose_name_plural": "Direct Sales",
                "ordering": ["-sale_date"],
            },
        ),
    ]
