# Generated by Django 4.2.23 on 2025-07-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0034_directsale"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="View Count"),
        ),
    ]
