# Generated by Django 4.2.23 on 2025-07-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0035_marketplaceproduct_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceproduct",
            name="recent_purchases_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this product was purchased in the last 24 hours. Used for popularity ranking.",
                verbose_name="Recent Purchases (24h)",
            ),
        ),
    ]
