# Generated by Django 4.2.23 on 2025-07-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0036_alter_marketplaceproduct_recent_purchases_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='rank_score',
            field=models.FloatField(default=0, verbose_name='Rank Score'),
        ),
    ]
