# Generated by Django 4.2.26 on 2025-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0045_marketplaceproduct_is_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="is_made_in_nepal",
            field=models.BooleanField(
                default=False, help_text="Indicates if this product is made in Nepal", verbose_name="Made in Nepal"
            ),
        ),
    ]
