# Generated by Django 4.2.26 on 2025-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0046_marketplaceproduct_is_made_in_nepal"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="additional_information",
            field=models.TextField(
                blank=True,
                help_text="Any additional information about the marketplace product",
                null=True,
                verbose_name="Additional Information",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("YELLOW", "Yellow"),
                    ("BLACK", "Black"),
                    ("WHITE", "White"),
                    ("GRAY", "Gray"),
                    ("BROWN", "Brown"),
                    ("ORANGE", "Orange"),
                    ("PURPLE", "Purple"),
                    ("PINK", "Pink"),
                    ("NAVY", "Navy"),
                    ("BEIGE", "Beige"),
                    ("GOLD", "Gold"),
                    ("SILVER", "Silver"),
                    ("MULTICOLOR", "Multicolor"),
                    ("TRANSPARENT", "Transparent"),
                    ("CUSTOM", "Custom Color"),
                ],
                help_text="Color of the marketplace product",
                max_length=20,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                    ("XXXL", "Triple Extra Large"),
                    ("ONE_SIZE", "One Size"),
                    ("CUSTOM", "Custom Size"),
                ],
                help_text="Size of the marketplace product",
                max_length=20,
                null=True,
                verbose_name="Size",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="additional_information",
            field=models.TextField(
                blank=True,
                help_text="Any additional information about the product",
                null=True,
                verbose_name="Additional Information",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("YELLOW", "Yellow"),
                    ("BLACK", "Black"),
                    ("WHITE", "White"),
                    ("GRAY", "Gray"),
                    ("BROWN", "Brown"),
                    ("ORANGE", "Orange"),
                    ("PURPLE", "Purple"),
                    ("PINK", "Pink"),
                    ("NAVY", "Navy"),
                    ("BEIGE", "Beige"),
                    ("GOLD", "Gold"),
                    ("SILVER", "Silver"),
                    ("MULTICOLOR", "Multicolor"),
                    ("TRANSPARENT", "Transparent"),
                    ("CUSTOM", "Custom Color"),
                ],
                help_text="Color of the product",
                max_length=20,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                    ("XXXL", "Triple Extra Large"),
                    ("ONE_SIZE", "One Size"),
                    ("CUSTOM", "Custom Size"),
                ],
                help_text="Size of the product",
                max_length=20,
                null=True,
                verbose_name="Size",
            ),
        ),
    ]
