# Generated by Django 4.2.26 on 2025-11-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0047_marketplaceproduct_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stock Keeping Unit (SKU)'),
        ),
    ]
