# Generated by Django 4.2.26 on 2025-12-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0048_alter_product_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Brand Name")),
                ("description", models.TextField(blank=True, verbose_name="Brand Description")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brand_logos/", verbose_name="Brand Logo")),
                ("website", models.URLField(blank=True, null=True, verbose_name="Website")),
                ("country_of_origin", models.CharField(blank=True, max_length=100, verbose_name="Country of Origin")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active Status")),
                ("is_verified", models.BooleanField(default=False, verbose_name="Verified Brand")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Update Time")),
                ("manufacturer_info", models.TextField(blank=True, verbose_name="Manufacturer Information")),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Contact Email")),
                ("contact_phone", models.CharField(blank=True, max_length=20, verbose_name="Contact Phone")),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="producer.brand",
                verbose_name="Brand",
            ),
        ),
    ]
