# Generated by Django 4.2.26 on 2025-12-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0049_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="b2b_min_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum order quantity for B2B pricing",
                null=True,
                verbose_name="B2B Minimum Quantity",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="b2b_price",
            field=models.FloatField(
                blank=True,
                help_text="Special pricing for B2B customers (distributors/retailers)",
                null=True,
                verbose_name="B2B Price",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="enable_b2b_sales",
            field=models.BooleanField(
                default=False,
                help_text="Allow verified businesses to purchase this product at special B2B rates",
                verbose_name="Enable B2B Sales",
            ),
        ),
        migrations.CreateModel(
            name="B2BPriceTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("distributor", "Distributor"), ("retailer", "Retailer"), ("wholesaler", "Wholesaler")],
                        max_length=20,
                        verbose_name="Customer Type",
                    ),
                ),
                ("min_quantity", models.PositiveIntegerField(verbose_name="Minimum Quantity")),
                ("price_per_unit", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price Per Unit")),
                (
                    "discount_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Optional additional discount percentage on top of the price per unit",
                        null=True,
                        verbose_name="Discount Percentage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_price_tiers",
                        to="producer.marketplaceproduct",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "B2B Price Tier",
                "verbose_name_plural": "B2B Price Tiers",
                "ordering": ["customer_type", "min_quantity"],
                "unique_together": {("product", "customer_type", "min_quantity")},
            },
        ),
    ]
