# Generated by Django 4.2.26 on 2025-12-02 08:00
# Step 1: Add B2B fields to MarketplaceProduct

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0049_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="enable_b2b_sales",
            field=models.BooleanField(
                default=False,
                verbose_name="Enable B2B Sales",
                help_text="Allow verified businesses to purchase this product at special B2B rates",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="b2b_price",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="B2B Price",
                help_text="Special pricing for B2B customers (distributors/retailers)",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="b2b_min_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="B2B Minimum Quantity",
                help_text="Minimum order quantity for B2B pricing",
            ),
        ),
    ]
