# Generated by Django 4.2.26 on 2025-12-02 07:05
# OPTIMIZED VERSION - Single SQL operation

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0049_brand_product_brand"),
    ]

    operations = [
        # Create B2BPriceTier first (fast, no existing data)
        migrations.CreateModel(
            name="B2BPriceTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("distributor", "Distributor"), ("retailer", "Retailer"), ("wholesaler", "Wholesaler")],
                        max_length=20,
                        verbose_name="Customer Type",
                    ),
                ),
                ("min_quantity", models.PositiveIntegerField(verbose_name="Minimum Quantity")),
                ("price_per_unit", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price Per Unit")),
                (
                    "discount_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Optional additional discount percentage on top of the price per unit",
                        null=True,
                        verbose_name="Discount Percentage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_price_tiers",
                        to="producer.marketplaceproduct",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "B2B Price Tier",
                "verbose_name_plural": "B2B Price Tiers",
                "ordering": ["customer_type", "min_quantity"],
            },
        ),
        
        # Ultra-fast: Add all columns without locking (PostgreSQL)
        migrations.RunSQL(
            sql="""
                ALTER TABLE producer_marketplaceproduct 
                ADD COLUMN IF NOT EXISTS enable_b2b_sales BOOLEAN DEFAULT FALSE,
                ADD COLUMN IF NOT EXISTS b2b_price FLOAT,
                ADD COLUMN IF NOT EXISTS b2b_min_quantity INTEGER;
                
                -- Set defaults quickly
                UPDATE producer_marketplaceproduct 
                SET enable_b2b_sales = FALSE 
                WHERE enable_b2b_sales IS NULL;
                
                ALTER TABLE producer_marketplaceproduct 
                ALTER COLUMN enable_b2b_sales SET NOT NULL,
                ALTER COLUMN enable_b2b_sales SET DEFAULT FALSE;
            """,
            reverse_sql="""
                ALTER TABLE producer_marketplaceproduct 
                DROP COLUMN IF EXISTS enable_b2b_sales,
                DROP COLUMN IF EXISTS b2b_price,
                DROP COLUMN IF EXISTS b2b_min_quantity;
            """,
            atomic=False  # Allow non-atomic for speed
        ),
        
        # Add unique constraint separately
        migrations.RunSQL(
            sql="""
                ALTER TABLE producer_b2bpricetier 
                ADD CONSTRAINT unique_product_customer_quantity 
                UNIQUE (product_id, customer_type, min_quantity);
            """,
            reverse_sql="""
                ALTER TABLE producer_b2bpricetier 
                DROP CONSTRAINT IF EXISTS unique_product_customer_quantity;
            """
        ),
    ]