# Generated by Django 4.2.26 on 2025-12-02 08:01
# Step 2: Create B2BPriceTier model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0050_add_b2b_fields_to_marketplaceproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BPriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("distributor", "Distributor"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                        ],
                        max_length=20,
                        verbose_name="Customer Type",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(verbose_name="Minimum Quantity"),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price Per Unit"),
                ),
                (
                    "discount_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Optional additional discount percentage on top of the price per unit",
                        null=True,
                        verbose_name="Discount Percentage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_price_tiers",
                        to="producer.marketplaceproduct",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "B2B Price Tier",
                "verbose_name_plural": "B2B Price Tiers",
                "ordering": ["customer_type", "min_quantity"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="b2bpricetier",
            unique_together={("product", "customer_type", "min_quantity")},
        ),
    ]
