# Generated by Django 4.2.26 on 2025-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0051_create_b2bpricetier_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="search_tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Keywords or tags for search optimization", verbose_name="Search Tags"
            ),
        ),
    ]
