# Generated by Django 4.2.27 on 2025-12-13 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0052_marketplaceproduct_search_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("handle", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=150, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="creator_avatars/")),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="creator_covers/")),
                ("is_verified", models.BooleanField(default=False)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("posts_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("public_collections_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("categories", models.ManyToManyField(blank=True, related_name="creators", to="producer.category")),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creators",
                        to="producer.city",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Creator Profile",
                "verbose_name_plural": "Creator Profiles",
            },
        ),
    ]
