# Generated by Django 4.2.27 on 2025-12-16 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0053_creatorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands",
                to="producer.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="sub_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands",
                to="producer.subsubcategory",
                verbose_name="Sub-subcategory",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands",
                to="producer.subcategory",
                verbose_name="Subcategory",
            ),
        ),
    ]
