# Generated by Django 4.2.27 on 2025-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0054_brand_category_brand_sub_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="made_for_you",
            field=models.BooleanField(
                default=False,
                help_text="Flag indicating the product is part of personalized 'made for you' recommendations",
                verbose_name="Made For You",
            ),
        ),
    ]
