# Generated by Django 4.2.27 on 2025-12-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0055_marketplaceproduct_made_for_you"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["user", "is_active", "category"], name="producer_pr_user_id_dde20d_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="producer_pr_price_edf11a_idx"),
        ),
    ]
