# Generated by Django 4.2.27 on 2026-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0045_shoppablevideocategory_shoppablevideo_category"),
        ("producer", "0057_marketplaceproduct_producer_ma_is_avai_c0ceee_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="video_categories",
            field=models.ManyToManyField(blank=True, related_name="creators", to="market.shoppablevideocategory"),
        ),
    ]
