# Generated by Django 4.2.27 on 2026-01-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0058_creatorprofile_video_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="creatorprofile",
            name="follower_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="creatorprofile",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
