# Generated by Django 4.2.27 on 2026-01-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0059_alter_creatorprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("YELLOW", "Yellow"),
                    ("BLACK", "Black"),
                    ("WHITE", "White"),
                    ("GRAY", "Gray"),
                    ("BROWN", "Brown"),
                    ("ORANGE", "Orange"),
                    ("PURPLE", "Purple"),
                    ("PINK", "Pink"),
                    ("NAVY", "Navy"),
                    ("BEIGE", "Beige"),
                    ("GOLD", "Gold"),
                    ("SILVER", "Silver"),
                    ("MULTICOLOR", "Multicolor"),
                    ("TRANSPARENT", "Transparent"),
                    ("CUSTOM", "Custom Color"),
                ],
                help_text="Color of the product",
                max_length=50,
                null=True,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                    ("XXXL", "Triple Extra Large"),
                    ("ONE_SIZE", "One Size"),
                    ("CUSTOM", "Custom Size"),
                ],
                help_text="Size of the product",
                max_length=50,
                null=True,
                verbose_name="Size",
            ),
        ),
    ]
