# Generated by Django 4.2.27 on 2026-01-21 00:09

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0060_alter_product_color_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceproduct",
            name="available_delivery_zones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of GeographicZone IDs where product is deliverable",
                verbose_name="Available Delivery Zones",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="enable_geo_restrictions",
            field=models.BooleanField(
                default=False,
                help_text="Restrict sales to specific geographic zones",
                verbose_name="Enable Geo Restrictions",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="max_delivery_distance_km",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum distance from seller location for delivery",
                null=True,
                verbose_name="Max Delivery Distance (km)",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="sale_restricted_to_regions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of SaleRegion IDs with restrictions",
                verbose_name="Sale Restricted to Regions",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="seller_geo_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Auto-synced from producer location",
                null=True,
                srid=4326,
                verbose_name="Seller Geographic Point",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="seller_location_lat",
            field=models.FloatField(
                blank=True,
                help_text="Denormalized for easier access",
                null=True,
                validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)],
                verbose_name="Seller Location Latitude",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceproduct",
            name="seller_location_lon",
            field=models.FloatField(
                blank=True,
                help_text="Denormalized for easier access",
                null=True,
                validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)],
                verbose_name="Seller Location Longitude",
            ),
        ),
        migrations.AddField(
            model_name="producer",
            name="service_radius_km",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Maximum distance from seller location for delivery",
                verbose_name="Service Radius (km)",
            ),
        ),
    ]
