# Generated by Django 4.2.28 on 2026-03-05 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0061_marketplaceproduct_available_delivery_zones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='discount_percentage',
            field=models.FloatField(default=0, help_text='Discount percentage to apply (0-100). Auto-calculates discounted_price.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage'),
        ),
    ]
