# Generated by Django 4.2.28 on 2026-09-18 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0063_marketplaceproduct_is_delivery_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTaxonomyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Keyword Key')),
                ('canonical', models.CharField(max_length=150, verbose_name='Canonical Name')),
                ('category', models.CharField(db_index=True, max_length=150, verbose_name='Target Category')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='Synonyms and Spoken Aliases')),
                ('trending_suggestions', models.JSONField(blank=True, default=list, verbose_name='Fallback Suggestions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Taxonomy Node',
                'verbose_name_plural': 'Search Taxonomy Nodes',
                'ordering': ['category', 'canonical'],
            },
        ),
        migrations.CreateModel(
            name='SearchIntentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_query', models.CharField(db_index=True, max_length=255, verbose_name='Raw Search Query')),
                ('extracted_terms', models.JSONField(blank=True, default=list, verbose_name='Extracted Search Terms')),
                ('inferred_intent', models.CharField(blank=True, max_length=150, null=True, verbose_name='Inferred Intent')),
                ('resolved_category', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Resolved Category')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Results Returned')),
                ('fallback_type', models.CharField(choices=[('none', 'Direct Match'), ('brand_substitute', 'Brand Substitute'), ('category', 'Category Fallback'), ('trending', 'Trending Fallback')], default='none', max_length=50, verbose_name='Fallback Executed')),
                ('context_metadata', models.JSONField(blank=True, default=dict, help_text='Stores unstructured context: filters applied, user location, price limits, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('clicked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_conversions', to='producer.marketplaceproduct', verbose_name='Converted Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search Intent Log',
                'verbose_name_plural': 'Search Intent Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['raw_query', 'created_at'], name='producer_se_raw_que_de5392_idx'), models.Index(fields=['fallback_type', 'hit_count'], name='producer_se_fallbac_8ec852_idx')],
            },
        ),
    ]
