"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from celery.schedules import crontab

BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=str,
    DJANGO_CORS_ORIGIN_REGEX_WHITELIST=(list, []),
    DJANGO_ADDITIONAL_ALLOWED_HOSTS=(list, []),
    # Database
    DB_NAME=str,
    DB_USER=str,
    DB_PASSWORD=str,
    DB_HOST=str,
    DB_PORT=(int, 5432),
    DJANGO_TIME_ZONE=(str, "UTC"),
    # Static, Media configs
    DJANGO_STATIC_URL=(str, "/static/"),
    DJANGO_MEDIA_URL=(str, "/media/"),
    # -- File System
    DJANGO_STATIC_ROOT=(str, os.path.join(BASE_DIR, "staticfiles")),
    DJANGO_MEDIA_ROOT=(str, os.path.join(BASE_DIR, "media")),
    # Redis
    CELERY_REDIS_URL=str,
    CACHE_REDIS_URL=str,
    BREVO_API_KEY=str,
    KHALTI_SECRET_KEY=str,
    ELASTIC_SEARCH_HOST=(str, None),
)

# Read environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("DJANGO_SECRET_KEY")

DEBUG = env("DJANGO_DEBUG")


ALLOWED_HOSTS = [
    "localhost",
    "0.0.0.0",
    *env("DJANGO_ADDITIONAL_ALLOWED_HOSTS"),
]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # External apps
    "admin_auto_filters",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "django_celery_beat",
    "anymail",
    "ckeditor",
    "haystack",
    # localapps
    "producer.apps.ProducerConfig",
    "market",
    "user",
    "report",
    "search_suggestions",
    "drf_spectacular",
    "transport",
    "payment",
    "notification.apps.NotificationConfig",
    "external_delivery.apps.ExternalDeliveryConfig",
    "recommendations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "main.security_middleware.SecurityHeadersMiddleware",  # Custom security headers
    "main.security_middleware.ServerInfoHidingMiddleware",  # Hide server information
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "main.middleware.RateLimitMiddleware",  # Rate limiting for login protection
    "main.middleware.LoginProtectionMiddleware",  # Login attempt tracking and cleanup
    # "main.security_middleware.APIKeyValidationMiddleware",  # API key validation
    "main.security_middleware.FileUploadSecurityMiddleware",  # File upload security
    "main.security_middleware.DataSanitizationMiddleware",  # Input sanitization
    "external_delivery.middleware.auth.ExternalAPIMiddleware",  # External API middleware
    "external_delivery.middleware.rate_limit.ExternalAPIRateLimit",  # External API rate limiting
    "external_delivery.middleware.rate_limit.APIQuotaMiddleware",  # API quota enforcement
    "external_delivery.middleware.rate_limit.RequestSizeMiddleware",  # Request size limiting
    "external_delivery.middleware.rate_limit.SecurityHeadersMiddleware",  # Additional security headers
    "main.middleware.EnsureSessionKeyMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates"), os.path.join(BASE_DIR, "market/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "HOST": env("DB_HOST"),
        "PORT": "5432",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "OPTIONS": {"options": "-c search_path=public"},
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "main.validators.CustomPasswordValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = env("DJANGO_TIME_ZONE")

USE_I18N = True

USE_TZ = True

# ============================================================================
# STATIC FILES CONFIGURATION
# Unified configuration for Django and Celery environments
# ============================================================================

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

# Static files directories - unified path for all environments
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets", "static"),  # Primary static files location
]

# Static files finders - consistent order for all environments
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Unified static and media roots - same path for production and Celery
STATIC_ROOT = os.path.join(BASE_DIR, "assets", "staticfiles")  # Unified location
MEDIA_ROOT = os.path.join(BASE_DIR, "assets", "media")  # Consistent with existing

# Static files storage - consistent configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Environment-specific static file handling
if not DEBUG:
    # Production mode - ensure static files are collected
    import os

    if not os.path.exists(STATIC_ROOT):
        os.makedirs(STATIC_ROOT, exist_ok=True)

    # Check if static files need to be collected
    if not os.listdir(STATIC_ROOT):
        pass
else:
    pass
    # Development mode - serve directly from source

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Define specific allowed origins
CORS_ALLOWED_ORIGINS = [
    "https://appmulyabazzar.com",
    "https://www.appmulyabazzar.com",
    "https://admin.appmulyabazzar.com",
]

# For development only
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ]
    )

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.appmulyabazzar\.com$",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",  # For API key authentication
]

# Minimize CORS header exposure in production
if not DEBUG:
    CORS_EXPOSE_HEADERS = []  # Don't expose any additional headers
    CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight for 24 hours
else:
    CORS_EXPOSE_HEADERS = ["content-type", "authorization"]  # Minimal for development

# Production-specific CORS settings
CORS_URLS_REGEX = r"^/api/.*$"  # Only apply CORS to API endpoints

# CSRF Trusted Origins - Allow cross-origin requests to API endpoints
CSRF_TRUSTED_ORIGINS = [
    "https://appmulyabazzar.com",
    "https://www.appmulyabazzar.com",
    "https://admin.appmulyabazzar.com",
]

# For development only
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
            "http://localhost:8000",
            "http://127.0.0.1:8000",
        ]
    )
# CORS_ALLOW_METHODS = (
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# )

# CORS_ALLOW_HEADERS = (
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
#     "sentry-trace",
# )


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "external_delivery.middleware.auth.ExternalAPIAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        # Using custom session auth that doesn't enforce CSRF for API endpoints
        "main.authentication.CSRFExemptSessionAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Keep spectacular for schema generation but disable public endpoints in production
# This prevents AttributeError while still hiding documentation from users
if not DEBUG:
    print("🔒 API documentation endpoints disabled in production")
else:
    print("📚 API documentation enabled in DEBUG mode")

# Disable API documentation in production but keep valid schema class
if not DEBUG:
    # Use basic DRF schema instead of None to avoid errors
    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "rest_framework.schemas.AutoSchema"
    # Remove spectacular from installed apps in production
    try:
        INSTALLED_APPS.remove("drf_spectacular")
        print("🔒 API documentation disabled in production")
    except ValueError:
        pass

CELERY_REDIS_URL = env("CELERY_REDIS_URL")
CELERY_BROKER_URL = CELERY_REDIS_URL
CELERY_RESULT_BACKEND = CELERY_REDIS_URL
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BEAT_SCHEDULE = {
    "move_large_stock_to_stocklist": {
        "task": "producer.tasks.move_large_stock_to_stocklist",
        "schedule": crontab(minute=0, hour="*/3"),
    },
    # "update-bid-end-dates-every-hour": {
    #     "task": "producer.tasks.update_bid_end_dates",
    #     "schedule": crontab(minute=0, hour="*"),
    # },
    "recalc_inventory_parameters": {
        "task": "producer.tasks.recalc_inventory_parameters",
        "schedule": crontab(minute=0, hour="*"),
    },
    "update-recent-purchases-hourly": {
        "task": "market.tasks.update_recent_purchases",
        "schedule": crontab(minute=0, hour="*"),
    },
    # Notification tasks
    "send-scheduled-notifications": {
        "task": "notification.tasks.send_scheduled_notifications_task",
        "schedule": crontab(minute="*/5"),  # Every 5 minutes
    },
    "retry-failed-notifications": {
        "task": "notification.tasks.retry_failed_notifications_task",
        "schedule": crontab(minute=0, hour="*/2"),  # Every 2 hours
    },
    "cleanup-old-notifications": {
        "task": "notification.tasks.cleanup_old_notifications_task",
        "schedule": crontab(minute=0, hour=2),  # Daily at 2 AM
    },
    "update-device-token-status": {
        "task": "notification.tasks.update_device_token_status_task",
        "schedule": crontab(minute=0, hour=4),  # Daily at 4 AM
    },
    "generate-notification-analytics": {
        "task": "notification.tasks.generate_notification_analytics_task",
        "schedule": crontab(minute=0, hour=6),  # Daily at 6 AM
    },
    "process-notification-queue": {
        "task": "notification.tasks.process_notification_queue_task",
        "schedule": crontab(minute="*/2"),  # Every 2 minutes
    },
    # Transport tasks
    "periodic-delivery-reminders": {
        "task": "transport.celery_tasks.periodic_delivery_reminders",
        "schedule": crontab(minute="*/15"),  # Every 15 minutes
    },
    "periodic-cleanup-deliveries": {
        "task": "transport.celery_tasks.periodic_cleanup",
        "schedule": crontab(minute=0, hour=1),  # Daily at 1 AM
    },
    "periodic-delivery-estimate-updates": {
        "task": "transport.celery_tasks.periodic_estimate_updates",
        "schedule": crontab(minute=0, hour="*/6"),  # Every 6 hours
    },
    # User security tasks
    "cleanup-expired-login-attempts": {
        "task": "user.tasks.cleanup_login_attempts_task",
        "schedule": crontab(minute=0, hour=3),  # Daily at 3 AM
    },
    "security-stats-generation": {
        "task": "user.tasks.get_login_security_stats_task",
        "schedule": crontab(minute=0, hour=8),  # Daily at 8 AM
    },
    "update-query-associations-hourly": {
        "task": "search_suggestions.update_query_associations",
        "schedule": 3600.0,  # Every hour
    },
    # Update query popularity every 15 minutes
    "update-query-popularity-quarterly": {
        "task": "search_suggestions.update_query_popularity",
        "schedule": 900.0,  # Every 15 minutes
    },
    # Clear stale cache daily
    "clear-stale-cache-daily": {
        "task": "search_suggestions.clear_stale_cache",
        "schedule": 86400.0,  # Every day
    },
    # Cleanup old data weekly
    "cleanup-old-data-weekly": {
        "task": "search_suggestions.cleanup_old_data",
        "schedule": 604800.0,  # Every week
    },
    # Generate daily report at midnight
    "generate-daily-report": {
        "task": "search_suggestions.generate_daily_report",
        "schedule": 86400.0,  # Every day
        "kwargs": {"hour": 0, "minute": 0},  # At midnight
    },
    # Warm up cache every 6 hours
    "warmup-cache-6h": {
        "task": "search_suggestions.warmup_cache",
        "schedule": 21600.0,  # Every 6 hours
        "args": (100,),  # Cache 100 popular queries
    },
    "weekly-business-health-digest": {
        "task": "report.tasks.generate_weekly_business_digests",
        "schedule": crontab(hour=0, minute=0, day_of_week="monday"),
    },
    "daily-inventory-monitor": {
        "task": "report.tasks.check_inventory_and_alert",
        "schedule": crontab(hour=9, minute=0),  # Check every morning at 9 AM
    },
    "weekly-customer-segmentation": {
        "task": "report.tasks.automated_rfm_segmentation",
        "schedule": crontab(hour=1, minute=0, day_of_week="monday"),
    },
    "recalc-inventory-params": {
        "task": "producer.tasks.recalc_inventory_parameters",
        "schedule": crontab(hour=2, minute=0),  # Sync EOQ/Safety Stock daily
    },
    "cleanup-reports": {
        "task": "report.tasks.cleanup_old_reports",
        "schedule": crontab(hour=3, minute=0, day_of_month="1"),  # Monthly cleanup
    },
    "cleanup-expired-locks": {
        "task": "negotiation.tasks.cleanup_expired_locks",
        "schedule": 60.0,  # Run every minute
    },
}

SITE_URL = "https://appmulyabazzar.com"

# Cache configuration: use Redis if provided, otherwise fall back to local memory cache.
# Set `CACHE_REDIS_URL` in environment to enable Redis caching (e.g. redis://redis:6379/1).
CACHE_REDIS_URL = env("CACHE_REDIS_URL") or os.environ.get("CACHE_REDIS_URL")
if CACHE_REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": CACHE_REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            },
        }
    }
else:
    # Development fallback (per-process, not shared between workers)
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

# Cache TTL defaults (seconds) used by application-level caches. Can be overridden
# by environment variables if desired.
PRODUCER_SEARCH_CACHE_TTL = int(os.environ.get("PRODUCER_SEARCH_CACHE_TTL", 30))
PRODUCER_LIST_CACHE_TTL = int(os.environ.get("PRODUCER_LIST_CACHE_TTL", 15))
TRENDING_CACHE_TTL = int(os.environ.get("TRENDING_CACHE_TTL", 20))

KHALTI_SECRET_KEY = env("KHALTI_SECRET_KEY")
KHALTI_BASE_URL = "https://khalti.com/api/v2/"
KHALTI_WEBSITE_URL = ""
KHALTI_RETURN_URL = "https://appmulyabazzar.com/payment/success/"


SMS_TOKEN = os.environ.get("SMS_TOKEN")
SMS_API_URL = os.environ.get("SMS_API_URL")
SMS_SENDER = os.environ.get("SMS_SENDER")

SPECTACULAR_SETTINGS = {
    "TITLE": "Mulya Bazzar API",
    "DESCRIPTION": "Mulya Bazzar API Documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {},
    "ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE": False,
    "SCHEMA_PATH_PREFIX": "/api/v1/",
    # Remove the problematic DEFAULT_GENERATOR_CLASS to use the default
}

# Disable spectacular endpoints in production but keep schema generation working
if not DEBUG:
    SPECTACULAR_SETTINGS.update(
        {
            "SERVE_INCLUDE_SCHEMA": False,
            "SERVE_PUBLIC": False,
        }
    )

SPARROWSMS_API_KEY = os.environ.get("SPARROWSMS_API_KEY")
SPARROWSMS_SENDER_ID = os.environ.get("SPARROWSMS_SENDER_ID")
SPARROWSMS_ENDPOINT = os.environ.get("SPARROWSMS_ENDPOINT")

EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
BREVO_API_KEY = os.environ.get("BREVO_API_KEY")
ANYMAIL = {
    "BREVO_API_KEY": env("BREVO_API_KEY"),
}

# ============================================================================
# SECURITY SETTINGS
# ============================================================================

# Session Security
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF protection
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# CSRF Security
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access
CSRF_COOKIE_SAMESITE = "Lax"
# CSRF_USE_SESSIONS = True  # Store CSRF token in session - Temporarily disabled for API compatibility

# Security Headers (Django built-in)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year HSTS in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Additional production security
if not DEBUG:
    # Hide server information
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

    # Hide Django version and server info
    import django

    django.VERSION_INFO = (0, 0, 0, "final", 0)  # Hide Django version

    # Disable server signature in error pages
    ADMINS = []  # Don't send error emails that reveal server info

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Login Protection Settings
LOGIN_ATTEMPT_LIMIT = 3  # Max failed attempts before account lockout
LOGIN_ATTEMPT_TIMEOUT = 900  # 15 minutes lockout duration
IP_RATE_LIMIT = 10  # Max requests per IP in time window
IP_RATE_LIMIT_WINDOW = 300  # 5 minute window for IP rate limiting

# API Security
API_KEY_HEADER = "X-API-Key"
SENSITIVE_ENDPOINTS = [
    "/admin/",
    "/api/v1/payments/",
    "/api/v1/user-profile/",
]

DEFAULT_FROM_EMAIL = "mulyabazzar@gmail.com"


CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
    }
}

# Notification Settings
FCM_SERVICE_ACCOUNT_KEY_PATH = os.environ.get("FCM_SERVICE_ACCOUNT_KEY_PATH")
APNS_TEAM_ID = os.environ.get("APNS_TEAM_ID")
APNS_KEY_ID = os.environ.get("APNS_KEY_ID")
APNS_KEY_PATH = os.environ.get("APNS_KEY_PATH")
APNS_BUNDLE_ID = os.environ.get("APNS_BUNDLE_ID")
APNS_USE_SANDBOX = os.environ.get("APNS_USE_SANDBOX", "True").lower() == "true"

# if not DEBUG:
#     SECURE_SSL_REDIRECT = True
#     SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Additional security configuration
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": True,  # Disable all existing loggers
#     "formatters": {
#         "verbose": {
#             "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname} {message}",
#             "style": "{",
#         },
#         "security": {
#             "format": "[SECURITY] {asctime} {levelname} {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "security_file": {
#             "level": "WARNING",
#             "class": "logging.handlers.RotatingFileHandler",
#             "filename": os.path.join(BASE_DIR, "logs", "security.log"),
#             "maxBytes": 10485760,  # 10MB
#             "backupCount": 5,
#             "formatter": "security",
#         },
#         "console": {
#             "level": "DEBUG" if DEBUG else "CRITICAL",  # Only show CRITICAL logs in production
#             "class": "logging.StreamHandler",
#             "formatter": "verbose" if DEBUG else "simple",
#         },
#         "null": {
#             "class": "logging.NullHandler",
#         },
#     },
#     "root": {
#         "level": "INFO" if DEBUG else "CRITICAL",
#         "handlers": ["console"] if DEBUG else ["null"],
#     },
#     "loggers": {
#         # Django core loggers
#         "django": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "INFO" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         "django.request": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         "django.db.backends": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         "django.server": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "INFO" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         # Third-party loggers
#         "rest_framework": {
#             "handlers": ["null"],
#             "level": "CRITICAL",
#             "propagate": False,
#         },
#         "celery": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "INFO" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "corsheaders": {
#             "handlers": ["null"],
#             "level": "CRITICAL",
#             "propagate": False,
#         },
#         # Application loggers
#         "user": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "market": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "producer": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "transport": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "payment": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "notification": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         # Security loggers (always active)
#         "security": {
#             "handlers": ["security_file"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#         "main.security_middleware": {
#             "handlers": ["security_file"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#         "main.middleware": {
#             "handlers": ["security_file"] if not DEBUG else ["security_file", "console"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#     },
# }

CELERY_STATIC_ROOT = STATIC_ROOT
CELERY_MEDIA_ROOT = MEDIA_ROOT


# Required for Django HayStack
ELASTIC_SEARCH_HOST = env("ELASTIC_SEARCH_HOST") or "http://elasticsearch:9200"

# Required for Django HayStack
HAYSTACK_CONNECTIONS = {
    "default": {
        "ENGINE": "haystack.backends.elasticsearch7_backend.Elasticsearch7SearchEngine",
        "URL": ELASTIC_SEARCH_HOST,
        "INDEX_NAME": "new_index",
    },
}

HAYSTACK_LIMIT_TO_REGISTERED_MODELS = False


# External Delivery API Settings
EXTERNAL_API_MAX_REQUEST_SIZE = 1024 * 1024  # 1MB
EXTERNAL_API_DEFAULT_RATE_LIMIT_MINUTE = 60
EXTERNAL_API_DEFAULT_RATE_LIMIT_HOUR = 1000

# Frontend base URL for tracking links
FRONTEND_BASE_URL = env("FRONTEND_BASE_URL", default="https://yourapp.com")

# Webhook settings
WEBHOOK_TIMEOUT = 30  # seconds
WEBHOOK_MAX_RETRIES = 3
WEBHOOK_RETRY_DELAYS = [60, 300, 900]  # 1 min, 5 min, 15 min

# External business limits by plan
EXTERNAL_PLAN_LIMITS = {
    "free": {
        "monthly_deliveries": 100,
        "rate_limit_minute": 30,
        "rate_limit_hour": 500,
    },
    "starter": {
        "monthly_deliveries": 500,
        "rate_limit_minute": 60,
        "rate_limit_hour": 1000,
    },
    "business": {
        "monthly_deliveries": 2000,
        "rate_limit_minute": 120,
        "rate_limit_hour": 2000,
    },
    "enterprise": {
        "monthly_deliveries": float("inf"),
        "rate_limit_minute": 300,
        "rate_limit_hour": 5000,
    },
}

# JWT Configuration for External Business Authentication
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
}

# External Delivery Integration Settings
EXTERNAL_API_MAX_REQUEST_SIZE = 1024 * 1024  # 1MB
FRONTEND_BASE_URL = env("FRONTEND_BASE_URL", default="https://yourapp.com")
WEBHOOK_TIMEOUT = 30
WEBHOOK_MAX_RETRIES = 3

NEGOTIATION_LOCK_TIMEOUT = 300  # 5 minutes
NEGOTIATION_EXPIRY_DAYS = 7
NEGOTIATION_VIEW_PERMISSION_DURATION = 3600  # 1 hour
