"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from celery.schedules import crontab

BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=str,
    DJANGO_CORS_ORIGIN_REGEX_WHITELIST=(list, []),
    DJANGO_ADDITIONAL_ALLOWED_HOSTS=(list, []),
    # Database
    DB_NAME=str,
    DB_USER=str,
    DB_PASSWORD=str,
    DB_HOST=str,
    DB_PORT=(int, 5432),
    DJANGO_TIME_ZONE=(str, "UTC"),
    # Static, Media configs
    DJANGO_STATIC_URL=(str, "/static/"),
    DJANGO_MEDIA_URL=(str, "/media/"),
    # -- File System
    DJANGO_STATIC_ROOT=(str, os.path.join(BASE_DIR, "staticfiles")),
    DJANGO_MEDIA_ROOT=(str, os.path.join(BASE_DIR, "media")),
    # Redis
    CELERY_REDIS_URL=str,
    CACHE_REDIS_URL=str,
    BREVO_API_KEY=str,
    KHALTI_SECRET_KEY=str,
)

# Read environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("DJANGO_SECRET_KEY")

DEBUG = env("DJANGO_DEBUG")


ALLOWED_HOSTS = [
    "localhost",
    "0.0.0.0",
    *env("DJANGO_ADDITIONAL_ALLOWED_HOSTS"),
]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    # External apps
    "admin_auto_filters",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_filters",
    "django_celery_beat",
    "anymail",
    "ckeditor",
    # localapps
    "producer.apps.ProducerConfig",
    "market",
    "user",
    "report",
    "drf_spectacular",
    "transport",
    "payment",
    "notification.apps.NotificationConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "main.security_middleware.SecurityHeadersMiddleware",  # Custom security headers
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "main.middleware.RateLimitMiddleware",  # Rate limiting for login protection
    "main.middleware.LoginProtectionMiddleware",  # Login attempt tracking and cleanup
    # "main.security_middleware.APIKeyValidationMiddleware",  # API key validation
    "main.security_middleware.FileUploadSecurityMiddleware",  # File upload security
    "main.security_middleware.DataSanitizationMiddleware",  # Input sanitization
    "main.middleware.EnsureSessionKeyMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates"), os.path.join(BASE_DIR, "market/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "HOST": env("DB_HOST"),
        "PORT": "5432",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "OPTIONS": {"options": "-c search_path=public"},
    },
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "main.validators.CustomPasswordValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = env("DJANGO_TIME_ZONE")

USE_I18N = True

USE_TZ = True

# ============================================================================
# STATIC FILES CONFIGURATION
# Unified configuration for Django and Celery environments
# ============================================================================

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

# Static files directories - unified path for all environments
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets", "static"),  # Primary static files location
]

# Static files finders - consistent order for all environments
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Unified static and media roots - same path for production and Celery
STATIC_ROOT = os.path.join(BASE_DIR, "assets", "staticfiles")  # Unified location
MEDIA_ROOT = os.path.join(BASE_DIR, "assets", "media")  # Consistent with existing

# Static files storage - consistent configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Environment-specific static file handling
if not DEBUG:
    # Production mode - ensure static files are collected
    import os

    if not os.path.exists(STATIC_ROOT):
        os.makedirs(STATIC_ROOT, exist_ok=True)

    # Check if static files need to be collected
    if not os.listdir(STATIC_ROOT):
        pass
else:
    pass
    # Development mode - serve directly from source

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Define specific allowed origins
CORS_ALLOWED_ORIGINS = [
    "https://appmulyabazzar.com",
    "https://www.appmulyabazzar.com",
    "https://admin.appmulyabazzar.com",
]

# For development only
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ]
    )

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.appmulyabazzar\.com$",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",  # For API key authentication
]

# Minimize CORS header exposure in production
if not DEBUG:
    CORS_EXPOSE_HEADERS = []  # Don't expose any additional headers
    CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight for 24 hours
else:
    CORS_EXPOSE_HEADERS = ["content-type", "authorization"]  # Minimal for development

# Production-specific CORS settings
CORS_URLS_REGEX = r"^/api/.*$"  # Only apply CORS to API endpoints
# CORS_ALLOW_METHODS = (
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# )

# CORS_ALLOW_HEADERS = (
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
#     "sentry-trace",
# )


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

CELERY_REDIS_URL = env("CELERY_REDIS_URL")
CELERY_BROKER_URL = CELERY_REDIS_URL
CELERY_RESULT_BACKEND = CELERY_REDIS_URL
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BEAT_SCHEDULE = {
    "move_large_stock_to_stocklist": {
        "task": "producer.tasks.move_large_stock_to_stocklist",
        "schedule": crontab(minute=0, hour="*/3"),
    },
    # "update-bid-end-dates-every-hour": {
    #     "task": "producer.tasks.update_bid_end_dates",
    #     "schedule": crontab(minute=0, hour="*"),
    # },
    "recalc_inventory_parameters": {
        "task": "producer.tasks.recalc_inventory_parameters",
        "schedule": crontab(minute=0, hour="*"),
    },
    "update-recent-purchases-hourly": {
        "task": "market.tasks.update_recent_purchases",
        "schedule": crontab(minute=0, hour="*"),
    },
    # Notification tasks
    "send-scheduled-notifications": {
        "task": "notification.tasks.send_scheduled_notifications_task",
        "schedule": crontab(minute="*/5"),  # Every 5 minutes
    },
    "retry-failed-notifications": {
        "task": "notification.tasks.retry_failed_notifications_task",
        "schedule": crontab(minute=0, hour="*/2"),  # Every 2 hours
    },
    "cleanup-old-notifications": {
        "task": "notification.tasks.cleanup_old_notifications_task",
        "schedule": crontab(minute=0, hour=2),  # Daily at 2 AM
    },
    "update-device-token-status": {
        "task": "notification.tasks.update_device_token_status_task",
        "schedule": crontab(minute=0, hour=4),  # Daily at 4 AM
    },
    "generate-notification-analytics": {
        "task": "notification.tasks.generate_notification_analytics_task",
        "schedule": crontab(minute=0, hour=6),  # Daily at 6 AM
    },
    "process-notification-queue": {
        "task": "notification.tasks.process_notification_queue_task",
        "schedule": crontab(minute="*/2"),  # Every 2 minutes
    },
    # Transport tasks
    "periodic-delivery-reminders": {
        "task": "transport.celery_tasks.periodic_delivery_reminders",
        "schedule": crontab(minute="*/15"),  # Every 15 minutes
    },
    "periodic-cleanup-deliveries": {
        "task": "transport.celery_tasks.periodic_cleanup",
        "schedule": crontab(minute=0, hour=1),  # Daily at 1 AM
    },
    "periodic-delivery-estimate-updates": {
        "task": "transport.celery_tasks.periodic_estimate_updates",
        "schedule": crontab(minute=0, hour="*/6"),  # Every 6 hours
    },
    # User security tasks
    "cleanup-expired-login-attempts": {
        "task": "user.tasks.cleanup_login_attempts_task",
        "schedule": crontab(minute=0, hour=3),  # Daily at 3 AM
    },
    "security-stats-generation": {
        "task": "user.tasks.get_login_security_stats_task",
        "schedule": crontab(minute=0, hour=8),  # Daily at 8 AM
    },
}

SITE_URL = "https://appmulyabazzar.com"

KHALTI_SECRET_KEY = env("KHALTI_SECRET_KEY")
KHALTI_BASE_URL = "https://khalti.com/api/v2/"
KHALTI_WEBSITE_URL = ""
KHALTI_RETURN_URL = "https://appmulyabazzar.com/payment/success/"


SMS_TOKEN = os.environ.get("SMS_TOKEN")
SMS_API_URL = os.environ.get("SMS_API_URL")
SMS_SENDER = os.environ.get("SMS_SENDER")

SPECTACULAR_SETTINGS = {
    "TITLE": "Mulya Bazzar API",
    "DESCRIPTION": "Mulya Bazzar API Documenation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {},
    "ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE": False,
}

SPARROWSMS_API_KEY = os.environ.get("SPARROWSMS_API_KEY")
SPARROWSMS_SENDER_ID = os.environ.get("SPARROWSMS_SENDER_ID")
SPARROWSMS_ENDPOINT = os.environ.get("SPARROWSMS_ENDPOINT")

EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
BREVO_API_KEY = os.environ.get("BREVO_API_KEY")
ANYMAIL = {
    "BREVO_API_KEY": env("BREVO_API_KEY"),
}

# ============================================================================
# SECURITY SETTINGS
# ============================================================================

# Session Security
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF protection
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# CSRF Security
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access
CSRF_COOKIE_SAMESITE = "Lax"
# CSRF_USE_SESSIONS = True  # Store CSRF token in session - Temporarily disabled for API compatibility

# Security Headers (Django built-in)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year HSTS in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Additional production security
if not DEBUG:
    # Hide server information
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

    # Hide Django version and server info
    import django

    django.VERSION_INFO = (0, 0, 0, "final", 0)  # Hide Django version

    # Disable server signature in error pages
    ADMINS = []  # Don't send error emails that reveal server info

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Login Protection Settings
LOGIN_ATTEMPT_LIMIT = 3  # Max failed attempts before account lockout
LOGIN_ATTEMPT_TIMEOUT = 900  # 15 minutes lockout duration
IP_RATE_LIMIT = 10  # Max requests per IP in time window
IP_RATE_LIMIT_WINDOW = 300  # 5 minute window for IP rate limiting

# API Security
API_KEY_HEADER = "X-API-Key"
SENSITIVE_ENDPOINTS = [
    "/admin/",
    "/api/v1/payments/",
    "/api/v1/user-profile/",
]

DEFAULT_FROM_EMAIL = "mulyabazzar@gmail.com"


CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
    }
}

# Notification Settings
FCM_SERVICE_ACCOUNT_KEY_PATH = os.environ.get("FCM_SERVICE_ACCOUNT_KEY_PATH")
APNS_TEAM_ID = os.environ.get("APNS_TEAM_ID")
APNS_KEY_ID = os.environ.get("APNS_KEY_ID")
APNS_KEY_PATH = os.environ.get("APNS_KEY_PATH")
APNS_BUNDLE_ID = os.environ.get("APNS_BUNDLE_ID")
APNS_USE_SANDBOX = os.environ.get("APNS_USE_SANDBOX", "True").lower() == "true"

# if not DEBUG:
#     SECURE_SSL_REDIRECT = True
#     SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Additional security configuration
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": True,  # Disable all existing loggers
#     "formatters": {
#         "verbose": {
#             "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname} {message}",
#             "style": "{",
#         },
#         "security": {
#             "format": "[SECURITY] {asctime} {levelname} {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "security_file": {
#             "level": "WARNING",
#             "class": "logging.handlers.RotatingFileHandler",
#             "filename": os.path.join(BASE_DIR, "logs", "security.log"),
#             "maxBytes": 10485760,  # 10MB
#             "backupCount": 5,
#             "formatter": "security",
#         },
#         "console": {
#             "level": "DEBUG" if DEBUG else "CRITICAL",  # Only show CRITICAL logs in production
#             "class": "logging.StreamHandler",
#             "formatter": "verbose" if DEBUG else "simple",
#         },
#         "null": {
#             "class": "logging.NullHandler",
#         },
#     },
#     "root": {
#         "level": "INFO" if DEBUG else "CRITICAL",
#         "handlers": ["console"] if DEBUG else ["null"],
#     },
#     "loggers": {
#         # Django core loggers
#         "django": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "INFO" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         "django.request": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         "django.db.backends": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         "django.server": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "INFO" if DEBUG else "CRITICAL",
#             "propagate": False,
#         },
#         # Third-party loggers
#         "rest_framework": {
#             "handlers": ["null"],
#             "level": "CRITICAL",
#             "propagate": False,
#         },
#         "celery": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "INFO" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "corsheaders": {
#             "handlers": ["null"],
#             "level": "CRITICAL",
#             "propagate": False,
#         },
#         # Application loggers
#         "user": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "market": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "producer": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "transport": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "payment": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         "notification": {
#             "handlers": ["console"] if DEBUG else ["null"],
#             "level": "DEBUG" if DEBUG else "ERROR",
#             "propagate": False,
#         },
#         # Security loggers (always active)
#         "security": {
#             "handlers": ["security_file"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#         "main.security_middleware": {
#             "handlers": ["security_file"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#         "main.middleware": {
#             "handlers": ["security_file"] if not DEBUG else ["security_file", "console"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#     },
# }

CELERY_STATIC_ROOT = STATIC_ROOT
CELERY_MEDIA_ROOT = MEDIA_ROOT
