# Generated by Django 4.2.27 on 2026-01-16 09:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "points_per_unit",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of points earned per unit amount", verbose_name="Points Per Unit"
                    ),
                ),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Currency amount that equals one unit (e.g., 100 NPR)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Unit Amount",
                    ),
                ),
                (
                    "points_expiry_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days until earned points expire (null = never expire)",
                        null=True,
                        verbose_name="Points Expiry Days",
                    ),
                ),
                (
                    "min_redemption_points",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Minimum points required for redemption",
                        verbose_name="Minimum Redemption Points",
                    ),
                ),
                (
                    "max_redemption_points",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum points that can be redeemed in one transaction",
                        null=True,
                        verbose_name="Maximum Redemption Points",
                    ),
                ),
                (
                    "allow_negative_balance",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to have negative point balance",
                        verbose_name="Allow Negative Balance",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loyalty Configuration",
                "verbose_name_plural": "Loyalty Configurations",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyPerk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Perk Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "code",
                    models.SlugField(
                        blank=True, help_text="Unique code for programmatic access to perks", null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loyalty Perk",
                "verbose_name_plural": "Loyalty Perks",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Tier Name")),
                (
                    "min_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lifetime points required to reach this tier",
                        verbose_name="Minimum Points Required",
                    ),
                ),
                (
                    "point_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Multiplier for points earned at this tier (e.g., 1.50 for 50% bonus)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("99.99")),
                        ],
                        verbose_name="Point Multiplier",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive tiers cannot be assigned to users", verbose_name="Is Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loyalty Tier",
                "verbose_name_plural": "Loyalty Tiers",
                "ordering": ["min_points"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransactionArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField(db_index=True)),
                ("username", models.CharField(max_length=150)),
                ("points", models.IntegerField()),
                ("transaction_type", models.CharField(max_length=15)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("purchase_id", models.CharField(blank=True, max_length=100, null=True)),
                ("reference_id", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("balance_after", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Loyalty Transaction Archive",
                "verbose_name_plural": "Loyalty Transaction Archives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLoyalty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, help_text="Available points for redemption", verbose_name="Current Points"
                    ),
                ),
                (
                    "lifetime_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total points earned over all time (determines tier)",
                        verbose_name="Lifetime Points",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive profiles cannot earn or redeem points", verbose_name="Is Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tier_updated_at", models.DateTimeField(blank=True, null=True, verbose_name="Tier Last Updated")),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loyalty.loyaltytier",
                        verbose_name="Current Tier",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Loyalty Profile",
                "verbose_name_plural": "User Loyalty Profiles",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "points",
                    models.IntegerField(
                        help_text="Positive for earned, negative for redeemed/expired", verbose_name="Points"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earned"),
                            ("redeem", "Redeemed"),
                            ("expire", "Expired"),
                            ("refund", "Refund"),
                            ("admin_add", "Admin Addition"),
                            ("admin_deduct", "Admin Deduction"),
                            ("bonus", "Bonus"),
                        ],
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "purchase_id",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name="Purchase ID"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier to prevent duplicate transactions",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional transaction data", verbose_name="Metadata"
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        help_text="Point balance after this transaction", verbose_name="Balance After"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this transaction (for admin adjustments)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "user_loyalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="loyalty.userloyalty",
                        verbose_name="User Loyalty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Transaction",
                "verbose_name_plural": "Loyalty Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loyaltytier",
            index=models.Index(fields=["min_points", "is_active"], name="loyalty_loy_min_poi_40f507_idx"),
        ),
        migrations.AddField(
            model_name="loyaltyperk",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perks",
                to="loyalty.loyaltytier",
                verbose_name="Tier",
            ),
        ),
        migrations.AddField(
            model_name="loyaltyconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddIndex(
            model_name="userloyalty",
            index=models.Index(fields=["user", "is_active"], name="loyalty_use_user_id_20d81c_idx"),
        ),
        migrations.AddIndex(
            model_name="userloyalty",
            index=models.Index(fields=["tier", "lifetime_points"], name="loyalty_use_tier_id_cbce70_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltytransaction",
            index=models.Index(fields=["-created_at", "user_loyalty"], name="loyalty_loy_created_a889e7_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltytransaction",
            index=models.Index(fields=["purchase_id", "transaction_type"], name="loyalty_loy_purchas_3536e4_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltytransaction",
            index=models.Index(fields=["reference_id"], name="loyalty_loy_referen_836601_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltytransaction",
            index=models.Index(fields=["transaction_type", "created_at"], name="loyalty_loy_transac_7a8030_idx"),
        ),
        migrations.AddIndex(
            model_name="loyaltyperk",
            index=models.Index(fields=["code", "is_active"], name="loyalty_loy_code_7872a0_idx"),
        ),
    ]
