# Generated by Django 4.2.27 on 2026-01-20 13:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0060_alter_product_color_alter_product_name_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertThreshold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("supplier_health", "Supplier Health Alert"),
                            ("otif", "OTIF Rate Alert"),
                            ("lead_time", "Lead Time Alert"),
                            ("stock_low", "Low Stock Alert"),
                            ("stock_out", "Stock Out Alert"),
                            ("delayed_order", "Delayed Order"),
                            ("quality_issue", "Quality Issue"),
                            ("inventory_variance", "Inventory Variance"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "critical_threshold",
                    models.FloatField(help_text="Value that triggers CRITICAL alert", verbose_name="Critical Threshold"),
                ),
                ("critical_enabled", models.BooleanField(default=True, verbose_name="Critical Enabled")),
                (
                    "warning_threshold",
                    models.FloatField(help_text="Value that triggers WARNING alert", verbose_name="Warning Threshold"),
                ),
                ("warning_enabled", models.BooleanField(default=True, verbose_name="Warning Enabled")),
                (
                    "check_frequency_minutes",
                    models.IntegerField(
                        default=120, help_text="How often to check this threshold", verbose_name="Check Frequency (minutes)"
                    ),
                ),
                (
                    "auto_resolve_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Auto-resolve if condition normalizes for N hours",
                        verbose_name="Auto-Resolve Window (hours)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Threshold Configuration",
                "verbose_name_plural": "Alert Threshold Configurations",
            },
        ),
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "supplier_risk_level",
                    models.CharField(
                        choices=[("low", "Low Risk"), ("medium", "Medium Risk"), ("high", "High Risk")],
                        default="low",
                        max_length=20,
                        verbose_name="Supplier Risk Level",
                    ),
                ),
                (
                    "supplier_high_risk_count",
                    models.IntegerField(
                        default=0, help_text="Count of suppliers with score < 70", verbose_name="High Risk Suppliers Count"
                    ),
                ),
                (
                    "supplier_spend_at_risk",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="$ amount in last 90 days",
                        max_digits=15,
                        verbose_name="Supplier Spend At Risk",
                    ),
                ),
                (
                    "single_source_dependencies",
                    models.IntegerField(
                        default=0, help_text="Products from single supplier only", verbose_name="Single Source Dependencies"
                    ),
                ),
                (
                    "logistics_risk_level",
                    models.CharField(
                        choices=[("low", "Low Risk"), ("medium", "Medium Risk"), ("high", "High Risk")],
                        default="low",
                        max_length=20,
                        verbose_name="Logistics Risk Level",
                    ),
                ),
                (
                    "active_shipment_delays",
                    models.IntegerField(
                        default=0, help_text="Count of delayed deliveries", verbose_name="Active Shipment Delays"
                    ),
                ),
                ("avg_delay_days", models.FloatField(default=0, verbose_name="Average Delay (days)")),
                ("routes_with_issues", models.IntegerField(default=0, verbose_name="Routes With Issues")),
                (
                    "demand_risk_level",
                    models.CharField(
                        choices=[("low", "Low Risk"), ("medium", "Medium Risk"), ("high", "High Risk")],
                        default="low",
                        max_length=20,
                        verbose_name="Demand Risk Level",
                    ),
                ),
                ("forecast_accuracy", models.FloatField(default=0, verbose_name="Forecast Accuracy %")),
                (
                    "volatile_products_count",
                    models.IntegerField(
                        default=0, help_text="High demand variability", verbose_name="Volatile Products Count"
                    ),
                ),
                (
                    "stockout_incidents",
                    models.IntegerField(default=0, help_text="Last 30 days", verbose_name="Stock Out Incidents"),
                ),
                (
                    "inventory_risk_level",
                    models.CharField(
                        choices=[("low", "Low Risk"), ("medium", "Medium Risk"), ("high", "High Risk")],
                        default="low",
                        max_length=20,
                        verbose_name="Inventory Risk Level",
                    ),
                ),
                ("items_below_safety_stock", models.IntegerField(default=0, verbose_name="Items Below Safety Stock")),
                (
                    "overstock_items_count",
                    models.IntegerField(default=0, help_text="> 180 days supply", verbose_name="Overstock Items Count"),
                ),
                (
                    "total_inventory_value_at_risk",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Total Inventory Value At Risk"
                    ),
                ),
                ("overall_risk_score", models.FloatField(default=0, verbose_name="Overall Risk Score")),
                (
                    "overall_risk_level",
                    models.CharField(
                        choices=[("low", "Low Risk"), ("medium", "Medium Risk"), ("high", "High Risk")],
                        db_index=True,
                        default="low",
                        max_length=20,
                        verbose_name="Overall Risk Level",
                    ),
                ),
                ("snapshot_date", models.DateField(auto_now_add=True, verbose_name="Snapshot Date")),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="Last Updated")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = global/aggregate risks",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_categories",
                        to="producer.producer",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Category",
                "verbose_name_plural": "Risk Categories",
                "ordering": ["-snapshot_date"],
                "get_latest_by": "snapshot_date",
            },
        ),
        migrations.CreateModel(
            name="ProductDefectRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "defect_type",
                    models.CharField(
                        choices=[
                            ("quality", "Quality Issue"),
                            ("damage", "Damage"),
                            ("missing_items", "Missing Items"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Defect Type",
                    ),
                ),
                ("quantity_defective", models.IntegerField(verbose_name="Quantity Defective")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved"), ("escalated", "Escalated")],
                        default="open",
                        max_length=20,
                        verbose_name="Resolution Status",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                ("resolution_notes", models.TextField(blank=True, verbose_name="Resolution Notes")),
                ("defect_date", models.DateTimeField(auto_now_add=True, verbose_name="Defect Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="defect_records",
                        to="producer.order",
                        verbose_name="Related Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_records",
                        to="producer.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_records",
                        to="producer.producer",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Defect Record",
                "verbose_name_plural": "Product Defect Records",
                "ordering": ["-defect_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplyChainKPI",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("otif_rate", models.FloatField(default=0, verbose_name="OTIF Rate %")),
                ("otif_previous", models.FloatField(default=0, verbose_name="OTIF Previous %")),
                ("otif_trend_pct", models.FloatField(default=0, verbose_name="OTIF Trend %")),
                (
                    "lead_time_variability",
                    models.FloatField(
                        default=0, help_text="Standard deviation", verbose_name="Lead Time Variability (days)"
                    ),
                ),
                ("lead_time_avg", models.FloatField(default=0, verbose_name="Average Lead Time (days)")),
                ("lead_time_trend", models.FloatField(default=0, verbose_name="Lead Time Trend (days)")),
                ("inventory_turnover_ratio", models.FloatField(default=0, verbose_name="Inventory Turnover Ratio")),
                ("inventory_turnover_previous", models.FloatField(default=0, verbose_name="Inventory Turnover Previous")),
                ("inventory_trend_pct", models.FloatField(default=0, verbose_name="Inventory Trend %")),
                ("stock_out_incidents", models.IntegerField(default=0, verbose_name="Stock Out Incidents")),
                ("low_stock_items_count", models.IntegerField(default=0, verbose_name="Low Stock Items Count")),
                ("orders_pending_count", models.IntegerField(default=0, verbose_name="Pending Orders Count")),
                ("orders_delayed_count", models.IntegerField(default=0, verbose_name="Delayed Orders Count")),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                ("snapshot_date", models.DateField(auto_now_add=True, verbose_name="Snapshot Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = global/aggregate KPIs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_snapshots",
                        to="producer.producer",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Chain KPI",
                "verbose_name_plural": "Supply Chain KPIs",
                "ordering": ["-snapshot_date"],
                "get_latest_by": "snapshot_date",
                "indexes": [
                    models.Index(fields=["supplier", "snapshot_date"], name="risk_supply_supplie_343391_idx"),
                    models.Index(fields=["snapshot_date"], name="risk_supply_snapsho_ca2a45_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplyChainAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alert_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Alert ID")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("supplier_health", "Supplier Health Alert"),
                            ("otif", "OTIF Rate Alert"),
                            ("lead_time", "Lead Time Alert"),
                            ("stock_low", "Low Stock Alert"),
                            ("stock_out", "Stock Out Alert"),
                            ("delayed_order", "Delayed Order"),
                            ("quality_issue", "Quality Issue"),
                            ("inventory_variance", "Inventory Variance"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Immediate Action"),
                            ("warning", "Warning - Review Soon"),
                            ("info", "Info - FYI"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("auto_resolved", "Auto-Resolved"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="Object ID")),
                ("metric_value", models.FloatField(blank=True, null=True, verbose_name="Metric Value")),
                ("threshold_value", models.FloatField(blank=True, null=True, verbose_name="Threshold Value")),
                ("triggered_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Triggered At")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True, verbose_name="Acknowledged At")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                (
                    "auto_resolve_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Alert automatically resolved if condition normalizes for 24 hours",
                        null=True,
                        verbose_name="Auto-Resolve At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional context (previous_value, trend, etc.)", verbose_name="Metadata"
                    ),
                ),
                ("is_notified", models.BooleanField(default=False, verbose_name="Is Notified")),
                (
                    "notification_channels",
                    models.JSONField(
                        default=list, help_text="['email', 'push', 'in_app']", verbose_name="Notification Channels"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="producer.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_chain_alerts",
                        to="producer.producer",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Chain Alert",
                "verbose_name_plural": "Supply Chain Alerts",
                "ordering": ["-triggered_at"],
                "get_latest_by": "triggered_at",
                "indexes": [
                    models.Index(fields=["supplier", "severity", "status"], name="risk_supply_supplie_1eb6c2_idx"),
                    models.Index(fields=["alert_type", "triggered_at"], name="risk_supply_alert_t_3bb805_idx"),
                    models.Index(fields=["status", "triggered_at"], name="risk_supply_status_74230d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierScoreHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("health_score", models.FloatField(verbose_name="Health Score")),
                (
                    "health_status",
                    models.CharField(
                        choices=[("healthy", "Healthy"), ("monitor", "Monitor"), ("critical", "Critical")],
                        max_length=20,
                        verbose_name="Health Status",
                    ),
                ),
                ("on_time_delivery_pct", models.FloatField(default=0, verbose_name="On-Time Delivery %")),
                ("quality_performance_pct", models.FloatField(default=100, verbose_name="Quality Performance %")),
                ("lead_time_consistency_pct", models.FloatField(default=100, verbose_name="Lead Time Consistency %")),
                ("recorded_at", models.DateTimeField(auto_now_add=True, verbose_name="Recorded At")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_history",
                        to="producer.producer",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Score History",
                "verbose_name_plural": "Supplier Score Histories",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["supplier", "recorded_at"], name="risk_suppli_supplie_283988_idx"),
                    models.Index(fields=["recorded_at"], name="risk_suppli_recorde_0d21aa_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierScorecard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "on_time_delivery_pct",
                    models.FloatField(
                        default=0, help_text="Percentage of orders delivered on-time", verbose_name="On-Time Delivery %"
                    ),
                ),
                (
                    "quality_performance_pct",
                    models.FloatField(default=100, help_text="100% - defect_rate", verbose_name="Quality Performance %"),
                ),
                (
                    "lead_time_consistency_pct",
                    models.FloatField(
                        default=100, help_text="Consistency rating of lead times", verbose_name="Lead Time Consistency %"
                    ),
                ),
                (
                    "payment_reliability_pct",
                    models.FloatField(
                        default=100, help_text="On-time payment percentage", verbose_name="Payment Reliability %"
                    ),
                ),
                (
                    "health_score",
                    models.FloatField(default=80, help_text="Weighted average (0-100)", verbose_name="Health Score"),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy (80-100)"),
                            ("monitor", "Monitor (60-79)"),
                            ("critical", "Critical (0-59)"),
                        ],
                        default="healthy",
                        max_length=20,
                        verbose_name="Health Status",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, help_text="Orders in 90-day window", verbose_name="Total Orders"),
                ),
                ("on_time_orders", models.IntegerField(default=0, verbose_name="On-Time Orders")),
                ("defect_count", models.IntegerField(default=0, verbose_name="Defect Count")),
                ("avg_lead_time_days", models.FloatField(default=0, verbose_name="Average Lead Time (days)")),
                (
                    "lead_time_variance",
                    models.FloatField(
                        default=0, help_text="Standard deviation of lead times", verbose_name="Lead Time Variance"
                    ),
                ),
                ("late_payments_count", models.IntegerField(default=0, verbose_name="Late Payments Count")),
                ("last_calculated", models.DateTimeField(auto_now=True, verbose_name="Last Calculated")),
                (
                    "calculation_period_start",
                    models.DateField(help_text="Start of 90-day evaluation window", verbose_name="Calculation Period Start"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.OneToOneField(
                        help_text="Producer/Supplier entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecard",
                        to="producer.producer",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Scorecard",
                "verbose_name_plural": "Supplier Scorecards",
                "indexes": [
                    models.Index(fields=["supplier"], name="risk_suppli_supplie_40fb3f_idx"),
                    models.Index(fields=["health_status"], name="risk_suppli_health__8903f1_idx"),
                    models.Index(fields=["last_calculated"], name="risk_suppli_last_ca_84b7df_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskDrillDown",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("supplier_health", "Supplier Health"),
                            ("lead_time", "Lead Time"),
                            ("inventory", "Inventory"),
                            ("demand_forecast", "Demand Forecast"),
                            ("shipment_delay", "Shipment Delay"),
                            ("quality", "Quality Issue"),
                        ],
                        max_length=50,
                        verbose_name="Risk Type",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("product", "Product"),
                            ("route", "Route"),
                            ("order", "Order"),
                            ("delivery", "Delivery"),
                        ],
                        max_length=20,
                        verbose_name="Item Type",
                    ),
                ),
                ("item_id", models.PositiveIntegerField(verbose_name="Item ID")),
                ("item_name", models.CharField(max_length=255, verbose_name="Item Name")),
                ("metric_value", models.FloatField(verbose_name="Metric Value")),
                ("threshold", models.FloatField(verbose_name="Threshold")),
                (
                    "status",
                    models.CharField(
                        choices=[("at_risk", "At Risk"), ("critical", "Critical"), ("warning", "Warning")],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "details",
                    models.JSONField(default=dict, help_text="Flexible field for extra context", verbose_name="Details"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "risk_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drill_downs",
                        to="risk.riskcategory",
                        verbose_name="Risk Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Drill Down",
                "verbose_name_plural": "Risk Drill Downs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["risk_category", "risk_type"], name="risk_riskdr_risk_ca_1a64bb_idx"),
                    models.Index(fields=["item_type", "status"], name="risk_riskdr_item_ty_c1e31c_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="riskcategory",
            index=models.Index(fields=["supplier", "snapshot_date"], name="risk_riskca_supplie_dbb118_idx"),
        ),
        migrations.AddIndex(
            model_name="riskcategory",
            index=models.Index(fields=["snapshot_date"], name="risk_riskca_snapsho_64b3cd_idx"),
        ),
        migrations.AddIndex(
            model_name="riskcategory",
            index=models.Index(fields=["overall_risk_level"], name="risk_riskca_overall_a15fe7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="riskcategory",
            unique_together={("supplier", "snapshot_date")},
        ),
        migrations.AddIndex(
            model_name="productdefectrecord",
            index=models.Index(fields=["supplier", "defect_date"], name="risk_produc_supplie_f862ac_idx"),
        ),
        migrations.AddIndex(
            model_name="productdefectrecord",
            index=models.Index(fields=["product", "resolution_status"], name="risk_produc_product_7b3f00_idx"),
        ),
        migrations.AddIndex(
            model_name="productdefectrecord",
            index=models.Index(fields=["defect_type"], name="risk_produc_defect__454032_idx"),
        ),
    ]
