# Generated by Django 4.2.23 on 2025-07-11 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0032_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_date", models.DateField(help_text="Date of sales covered", unique=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                "verbose_name": "Daily Sales Report",
                "verbose_name_plural": "Daily Sales Reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="DailySalesReportItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(help_text="Sale date (should match report.report_date)")),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_report_items",
                        to="producer.marketplaceproduct",
                    ),
                ),
                (
                    "product_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products_sold",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="report.dailysalesreport"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Sales Report Item",
                "verbose_name_plural": "Daily Sales Report Items",
                "ordering": ["-date", "product"],
            },
        ),
        migrations.AddIndex(
            model_name="dailysalesreport",
            index=models.Index(fields=["report_date"], name="report_dail_report__538e86_idx"),
        ),
        migrations.AddIndex(
            model_name="dailysalesreportitem",
            index=models.Index(fields=["date"], name="report_dail_date_ad7b30_idx"),
        ),
        migrations.AddIndex(
            model_name="dailysalesreportitem",
            index=models.Index(fields=["product"], name="report_dail_product_4ad64b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailysalesreportitem",
            unique_together={("report", "product", "customer", "unit_price")},
        ),
    ]
