# Generated by Django 4.2.27 on 2026-01-13 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0059_alter_creatorprofile_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyBusinessHealthDigest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("new_customers", models.PositiveIntegerField(default=0)),
                (
                    "inventory_health_score",
                    models.FloatField(default=0.0, help_text="0-100 score based on stockouts vs demand"),
                ),
                ("growth_rate", models.FloatField(default=0.0, help_text="Percentage growth compared to last week")),
                ("report_file", models.FileField(blank=True, null=True, upload_to="reports/weekly_digests/pdf/")),
                ("excel_report", models.FileField(blank=True, null=True, upload_to="reports/weekly_digests/excel/")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("notification_sent", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "top_product",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="producer.marketplaceproduct"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Business health Digest",
                "ordering": ["-end_date"],
                "indexes": [
                    models.Index(fields=["user", "end_date"], name="report_week_user_id_db54d2_idx"),
                    models.Index(fields=["generated_at"], name="report_week_generat_6c1322_idx"),
                    models.Index(fields=["is_archived"], name="report_week_is_arch_fa3983_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerRFMSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recency_score", models.IntegerField(default=0)),
                ("frequency_score", models.IntegerField(default=0)),
                ("monetary_score", models.IntegerField(default=0)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("champions", "Champions"),
                            ("loyal", "Loyal Customers"),
                            ("potential_loyalist", "Potential Loyalist"),
                            ("at_risk", "At Risk"),
                            ("hibernating", "Hibernating"),
                            ("lost", "Lost"),
                        ],
                        max_length=50,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rfm_segments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "shop_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_customer_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer RFM Segment",
                "indexes": [
                    models.Index(fields=["shop_owner", "segment"], name="report_cust_shop_ow_b650b8_idx"),
                    models.Index(
                        fields=["recency_score", "frequency_score", "monetary_score"], name="report_cust_recency_7c52af_idx"
                    ),
                ],
                "unique_together": {("customer", "shop_owner")},
            },
        ),
    ]
