# Generated by Django 4.2.16 on 2024-09-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_end_date',
        ),
    ]
