# Generated by Django 4.2.16 on 2024-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], default='esewa', max_length=20, verbose_name='Payment Method'),
        ),
    ]
