# Generated by Django 4.2.16 on 2024-09-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_payment_payment_method'),
        ('market', '0005_shippingaddress'),
    ]

    operations = [
    ]
