# Generated by Django 4.2.16 on 2024-09-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_marketplaceuserproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='suggested_bid',
            field=models.FloatField(blank=True, null=True, verbose_name='Suggested Bid Amount'),
        ),
    ]
