# Generated by Django 4.2.16 on 2024-10-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0022_city_product_location'),
        ('market', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceuserproduct',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location of the product', null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.city', verbose_name='Location'),
        ),
    ]
