# Generated by Django 4.2.16 on 2024-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0012_marketplaceuserproduct_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceuserproduct",
            name="unit",
            field=models.CharField(
                choices=[("KG", "KiloGram"), ("LT", "Liter")], default="KG", max_length=2, verbose_name="unit"
            ),
        ),
    ]
