# Generated by Django 4.2.16 on 2024-11-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0013_marketplaceuserproduct_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceuserproduct",
            name="bid_end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bid End Date"),
        ),
    ]
