# Generated by Django 4.2.23 on 2025-06-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_cart_delivery_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
