# Generated by Django 4.2.23 on 2025-06-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='market.cart'),
        ),
    ]
