# Generated by Django 4.2.23 on 2025-07-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0020_alter_delivery_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
