# Generated by Django 4.2.23 on 2025-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0021_delivery_latitude_delivery_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("in_app", "In-App"), ("email", "Email"), ("sms", "SMS")],
                default="in_app",
                max_length=10,
                verbose_name="Channel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("sale", "Sale"),
                    ("po", "Purchase Order"),
                    ("stock", "Stock"),
                    ("marketplace", "Marketplace"),
                    ("alert", "Alert"),
                ],
                default="alert",
                max_length=20,
                verbose_name="Notification Type",
            ),
        ),
    ]
