# Generated by Django 4.2.23 on 2025-07-14 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0033_product_projected_stockout_date_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0022_notification_channel_notification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketplaceuserproduct",
            name="bid_end_date",
        ),
        migrations.RemoveField(
            model_name="marketplaceuserproduct",
            name="image",
        ),
        migrations.AlterField(
            model_name="marketplaceuserproduct",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location of the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="producer.city",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceuserproduct",
            name="stock",
            field=models.PositiveIntegerField(verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="marketplaceuserproduct",
            name="unit",
            field=models.CharField(
                choices=[("KG", "Kilogram"), ("LT", "Liter")], default="KG", max_length=2, verbose_name="Unit"
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceuserproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Seller"
            ),
        ),
        migrations.CreateModel(
            name="UserProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="marketplace/products/%Y/%m/%d/", verbose_name="Image")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Alternative text for accessibility", max_length=255, verbose_name="Alt Text"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order of images for carousel display", verbose_name="Display Order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="market.marketplaceuserproduct",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["order"],
            },
        ),
    ]
