# Generated by Django 4.2.23 on 2025-07-16 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0034_directsale"),
        ("market", "0024_marketplacesale_marketplacesale_valid_buyer_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(blank=True, max_length=40, null=True, verbose_name="Session Key")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Address")),
                ("user_agent", models.CharField(blank=True, max_length=255, verbose_name="User Agent")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Viewed At")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="producer.marketplaceproduct",
                        verbose_name="Viewed Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Viewing User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product View",
                "verbose_name_plural": "Product Views",
                "indexes": [
                    models.Index(fields=["product", "timestamp"], name="market_prod_product_fb559d_idx"),
                    models.Index(fields=["session_key", "timestamp"], name="market_prod_session_4dda45_idx"),
                ],
            },
        ),
    ]
