# Generated by Django 4.2.23 on 2025-08-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0025_productview"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTrackingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255, verbose_name="Message")),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="Location")),
                ("latitude", models.FloatField(blank=True, null=True, verbose_name="Latitude")),
                ("longitude", models.FloatField(blank=True, null=True, verbose_name="Longitude")),
                ("metadata", models.JSONField(blank=True, null=True, verbose_name="Metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="market.marketplacesale",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Tracking Event",
                "verbose_name_plural": "Order Tracking Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order", "created_at"], name="market_orde_order_i_5a3cab_idx"),
                    models.Index(fields=["status", "created_at"], name="market_orde_status_5658d7_idx"),
                ],
            },
        ),
    ]
