# Generated by Django 4.2.23 on 2025-09-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0026_ordertrackingevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="email",
            field=models.CharField(default="test@gmail.com", max_length=255),
            preserve_default=False,
        ),
    ]
