# Generated by Django 4.2.25 on 2025-11-04 13:01

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0001_initial"),
        ("producer", "0041_alter_product_category"),
        ("market", "0030_deliveryinfo_marketplaceorder_marketplaceorderitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=50, unique=True, verbose_name="Invoice Number"),
                ),
                ("invoice_date", models.DateTimeField(auto_now_add=True, verbose_name="Invoice Date")),
                ("due_date", models.DateTimeField(verbose_name="Due Date")),
                ("customer_name", models.CharField(max_length=255, verbose_name="Customer Name")),
                ("customer_email", models.EmailField(max_length=254, verbose_name="Customer Email")),
                ("customer_phone", models.CharField(blank=True, max_length=20, verbose_name="Customer Phone")),
                ("billing_address", models.TextField(verbose_name="Billing Address")),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Subtotal")),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10, verbose_name="Tax Amount"),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10, verbose_name="Shipping Cost"),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Total Amount")),
                ("currency", models.CharField(default="NPR", max_length=3, verbose_name="Currency")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="invoices/pdf/", verbose_name="PDF File")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Sent At")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "marketplace_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="market.marketplaceorder",
                        verbose_name="Marketplace Order",
                    ),
                ),
                (
                    "marketplace_sale",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="market.marketplacesale",
                        verbose_name="Marketplace Sale",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="payment.paymenttransaction",
                        verbose_name="Payment Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=255, verbose_name="Product Name")),
                ("product_sku", models.CharField(blank=True, max_length=100, verbose_name="Product SKU")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Unit Price")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Total Price")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="market.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "marketplace_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="producer.marketplaceproduct",
                        verbose_name="Marketplace Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["invoice_number"], name="market_invo_invoice_34693a_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["customer"], name="market_invo_custome_201ff1_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="market_invo_status_4fd2d9_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["invoice_date"], name="market_invo_invoice_4702d5_idx"),
        ),
    ]
