# Generated by Django 4.2.26 on 2025-11-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0046_marketplaceproduct_is_made_in_nepal"),
        ("market", "0031_invoice_invoicelineitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name": "Delivery", "verbose_name_plural": "Deliveries"},
        ),
        migrations.AddField(
            model_name="delivery",
            name="actual_delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="additional_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_person_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_person_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_service",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Delivery Status",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="estimated_delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="marketplace_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_deliveries",
                to="market.marketplaceorder",
                verbose_name="Marketplace Order",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="marketplace_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_deliveries",
                to="market.marketplacesale",
                verbose_name="Marketplace Sale",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="producer.sale",
                verbose_name="Sale",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="shop_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="cart",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="delivery", to="market.cart"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketplacesale",
            name="delivery",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketplace_sale_delivery",
                to="market.delivery",
                verbose_name="Delivery Details",
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["delivery_status"], name="market_deli_deliver_656b72_idx"),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["tracking_number"], name="market_deli_trackin_a5ecf3_idx"),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["created_at"], name="market_deli_created_cc65b2_idx"),
        ),
    ]
