# Generated by Django 4.2.26 on 2025-12-02 07:05

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0032_alter_delivery_options_delivery_actual_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceorder",
            name="credit_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Amount of business credit applied to this order",
                max_digits=12,
                verbose_name="Credit Applied",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="is_b2b_order",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this is a business-to-business order with special pricing",
                verbose_name="Is B2B Order",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="net_payment_due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Due date for payment based on payment terms",
                null=True,
                verbose_name="Net Payment Due Date",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="payment_terms_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of days allowed for payment for B2B orders",
                null=True,
                verbose_name="Payment Terms (Days)",
            ),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="requires_invoice",
            field=models.BooleanField(
                default=False, help_text="B2B order that requires formal invoice generation", verbose_name="Requires Invoice"
            ),
        ),
    ]
