# Generated by Django 4.2.27 on 2025-12-08 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0052_marketplaceproduct_search_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0033_marketplaceorder_credit_applied_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppableVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("video_file", models.FileField(upload_to="shoppable_videos/", verbose_name="Video File")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="shoppable_videos/thumbnails/", verbose_name="Thumbnail"
                    ),
                ),
                ("title", models.CharField(default="", max_length=255, verbose_name="Video Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Views")),
                ("likes_count", models.PositiveIntegerField(default=0, verbose_name="Likes")),
                ("shares_count", models.PositiveIntegerField(default=0, verbose_name="Shares")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shoppable_videos",
                        to="producer.marketplaceproduct",
                        verbose_name="Product",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shoppable_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shoppable Video",
                "verbose_name_plural": "Shoppable Videos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="liked_videos", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="market.shoppablevideo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Like",
                "verbose_name_plural": "Video Likes",
                "unique_together": {("user", "video")},
            },
        ),
    ]
