# Generated by Django 4.2.27 on 2025-12-08 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0034_shoppablevideo_videolike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppablevideo",
            name="video_file",
            field=models.FileField(
                upload_to="shoppable_videos/",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "avi", "mov"])],
                verbose_name="Video File",
            ),
        ),
    ]
