# Generated by Django 4.2.27 on 2025-12-08 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0035_alter_shoppablevideo_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppablevideo",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="shoppablevideo",
            name="trend_score",
            field=models.FloatField(default=0.0, verbose_name="Trend Score"),
        ),
        migrations.CreateModel(
            name="VideoSave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="saved_videos", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="saves", to="market.shoppablevideo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Save",
                "verbose_name_plural": "Video Saves",
                "unique_together": {("user", "video")},
            },
        ),
    ]
