# Generated by Django 4.2.27 on 2025-12-08 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0052_marketplaceproduct_search_tags"),
        ("market", "0036_shoppablevideo_tags_shoppablevideo_trend_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppablevideo",
            name="additional_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_in_videos",
                to="producer.marketplaceproduct",
                verbose_name="Additional Products",
            ),
        ),
        migrations.AlterField(
            model_name="shoppablevideo",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoppable_videos",
                to="producer.marketplaceproduct",
                verbose_name="Primary Product",
            ),
        ),
        migrations.CreateModel(
            name="VideoReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("harassment", "Harassment"),
                            ("misleading", "Misleading Information"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Reason",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="market.shoppablevideo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Report",
                "verbose_name_plural": "Video Reports",
            },
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Comment Text")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="market.videocomment",
                        verbose_name="Parent Comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="market.shoppablevideo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Comment",
                "verbose_name_plural": "Video Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="following", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="followers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Follow",
                "verbose_name_plural": "User Follows",
                "unique_together": {("follower", "following")},
            },
        ),
    ]
