# Generated by Django 4.2.27 on 2025-12-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0038_affiliateclick_producttag"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="affiliateclick",
            index=models.Index(fields=["product", "created_at"], name="market_affi_product_78b85a_idx"),
        ),
        migrations.AddIndex(
            model_name="affiliateclick",
            index=models.Index(fields=["content_type", "object_id"], name="market_affi_content_a7a0a2_idx"),
        ),
    ]
