# Generated by Django 4.2.27 on 2025-12-13 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0053_creatorprofile"),
        ("market", "0039_affiliateclick_market_affi_product_78b85a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppablevideo",
            name="creator_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="producer.creatorprofile",
                verbose_name="Creator Profile",
            ),
        ),
        migrations.AlterField(
            model_name="shoppablevideo",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shoppable_videos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploader",
            ),
        ),
    ]
