# Generated by Django 4.2.27 on 2025-12-16 01:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0040_shoppablevideo_creator_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="is_first_order",
            field=models.BooleanField(default=False, verbose_name="Is First Order"),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="is_first_order",
            field=models.BooleanField(default=False, verbose_name="Is First Order"),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10, verbose_name="Shipping Cost"),
        ),
        migrations.AddField(
            model_name="marketplacesale",
            name="is_first_order",
            field=models.BooleanField(default=False, verbose_name="Is First Order"),
        ),
    ]
