# Generated by Django 4.2.27 on 2025-12-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0041_delivery_is_first_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="label_pdf",
            field=models.FileField(blank=True, null=True, upload_to="shipping_labels/"),
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="label_pdf",
            field=models.FileField(blank=True, null=True, upload_to="shipping_labels/"),
        ),
    ]
