# Generated by Django 4.2.27 on 2025-12-25 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0042_delivery_label_pdf_marketplaceorder_label_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, max_length=255, null=True, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_seller_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_seller_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Target User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Chat Message",
                "verbose_name_plural": "Seller Chat Messages",
            },
        ),
    ]
