# Generated by Django 4.2.27 on 2025-12-25 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producer", "0055_marketplaceproduct_made_for_you"),
        ("market", "0043_sellerchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerchatmessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Is Read"),
        ),
        migrations.CreateModel(
            name="ProductChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(verbose_name="Message")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="producer.product", verbose_name="Product"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Sender"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Chat Message",
                "verbose_name_plural": "Product Chat Messages",
                "ordering": ["-timestamp"],
            },
        ),
    ]
