# Generated by Django 4.2.27 on 2026-01-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0044_sellerchatmessage_is_read_productchatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppableVideoCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Category Name")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="video_categories/", verbose_name="Icon")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Shoppable Video Category",
                "verbose_name_plural": "Shoppable Video Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="shoppablevideo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="market.shoppablevideocategory",
                verbose_name="Category",
            ),
        ),
    ]
