# Generated by Django 4.2.27 on 2026-01-12 04:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0045_shoppablevideocategory_shoppablevideo_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppablevideo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Shoppable Content",
                "verbose_name_plural": "Shoppable Contents",
            },
        ),
        migrations.AddField(
            model_name="shoppablevideo",
            name="content_type",
            field=models.CharField(
                choices=[("VIDEO", "Video"), ("IMAGE", "Graphic/Single Image"), ("COLLECTION", "Collection/Carousel")],
                db_index=True,
                default="VIDEO",
                max_length=20,
                verbose_name="Content Type",
            ),
        ),
        migrations.AddField(
            model_name="shoppablevideo",
            name="embedding",
            field=models.JSONField(blank=True, null=True, verbose_name="Vector Embedding"),
        ),
        migrations.AddField(
            model_name="shoppablevideo",
            name="image_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="shoppable_graphics/", verbose_name="Image File (for Single Image)"
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="dwell_time",
            field=models.FloatField(blank=True, help_text="Duration in seconds (for video/page stay)", null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="market.shoppablevideo",
            ),
        ),
        migrations.AlterField(
            model_name="shoppablevideo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="shoppablevideo",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="shoppablevideo",
            name="trend_score",
            field=models.FloatField(db_index=True, default=0.0, verbose_name="Trend Score"),
        ),
        migrations.AlterField(
            model_name="shoppablevideo",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="shoppable_videos/",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "avi", "mov"])],
                verbose_name="Video File",
            ),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="event_type",
            field=models.CharField(
                db_index=True, help_text="Type of event (e.g., 'click', 'page_view', 'watch_time')", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="ShoppableVideoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        help_text="Image or video file for the carousel item",
                        upload_to="shoppable_content/items/",
                        verbose_name="Media File",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="shoppable_content/items/thumbnails/", verbose_name="Thumbnail"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Display Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.shoppablevideo",
                        verbose_name="Parent Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shoppable Content Item",
                "verbose_name_plural": "Shoppable Content Items",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
