# Generated by Django 4.2.27 on 2026-01-12 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0059_alter_creatorprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0046_alter_shoppablevideo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Proposed Price')),
                ('proposed_quantity', models.PositiveIntegerField(verbose_name='Proposed Quantity')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTER_OFFER', 'Counter Offer'), ('ORDERED', 'Ordered')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_negotiations', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('last_offer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_negotiation_offers', to=settings.AUTH_USER_MODEL, verbose_name='Last Offer By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='producer.marketplaceproduct', verbose_name='Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_negotiations', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Negotiation',
                'verbose_name_plural': 'Negotiations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='market.negotiation', verbose_name='Negotiation')),
                ('offer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Offer By')),
            ],
            options={
                'verbose_name': 'Negotiation History',
                'verbose_name_plural': 'Negotiation Histories',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='marketplaceorderitem',
            name='negotiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='market.negotiation', verbose_name='Applied Negotiation'),
        ),
    ]
