# Generated by Django 4.2.27 on 2026-01-13 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0047_negotiation_negotiationhistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="negotiation",
            name="lock_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Lock Expires At"),
        ),
        migrations.AddField(
            model_name="negotiation",
            name="lock_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_negotiations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lock Owner",
            ),
        ),
        migrations.AlterField(
            model_name="negotiation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("COUNTER_OFFER", "Counter Offer"),
                    ("ORDERED", "Ordered"),
                    ("LOCKED", "Locked for Negotiation"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(fields=["status", "updated_at"], name="market_nego_status_49c1c2_idx"),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(fields=["buyer", "status"], name="market_nego_buyer_i_0a749a_idx"),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(fields=["seller", "status"], name="market_nego_seller__cf9627_idx"),
        ),
    ]
