# Generated by Django 4.2.27 on 2026-01-17 13:43

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0048_negotiation_lock_expires_at_negotiation_lock_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceorder",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Discount Amount"),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="Case-insensitive unique code (e.g., SUMMER2024)",
                        max_length=50,
                        unique=True,
                        verbose_name="Coupon Code",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                        default="fixed",
                        max_length=20,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Discount Value",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Minimum Purchase Amount",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cap the discount if using percentage type",
                        max_digits=12,
                        null=True,
                        verbose_name="Maximum Discount Amount",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total times this coupon can be used across all users",
                        null=True,
                        verbose_name="Total Usage Limit",
                    ),
                ),
                (
                    "user_limit",
                    models.PositiveIntegerField(
                        default=1, help_text="Times a single user can use this coupon", verbose_name="User Limit"
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0, verbose_name="Used Count")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code", "is_active"], name="market_coup_code_b9e35e_idx"),
                    models.Index(fields=["start_date", "end_date"], name="market_coup_start_d_f6ea59_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="marketplaceorder",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="market.coupon",
                verbose_name="Applied Coupon",
            ),
        ),
    ]
