# Generated by Django 4.2.27 on 2026-01-25 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0061_marketplaceproduct_available_delivery_zones_and_more"),
        ("market", "0049_marketplaceorder_discount_amount_coupon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="producer.marketplaceproduct",
            ),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="event_type",
            field=models.CharField(
                db_index=True,
                help_text="Type of event (e.g., 'click', 'page_view', 'watch_time', 'product_view', 'cart_add')",
                max_length=100,
            ),
        ),
    ]
