# Generated by Django 4.2.27 on 2026-02-03 11:58

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0050_userinteraction_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesBannerStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "total_products_sold",
                    models.BigIntegerField(
                        default=0, help_text="Total quantity of products sold", verbose_name="Total Products Sold"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue from all sales",
                        max_digits=15,
                        verbose_name="Total Revenue",
                    ),
                ),
                (
                    "total_sales_count",
                    models.BigIntegerField(
                        default=0, help_text="Total number of sale transactions", verbose_name="Total Sales Count"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when statistics were last calculated",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of calculation period (null = all time)",
                        null=True,
                        verbose_name="Period Start",
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of calculation period (null = current time)",
                        null=True,
                        verbose_name="Period End",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Banner Statistics",
                "verbose_name_plural": "Sales Banner Statistics",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.AddConstraint(
            model_name="salesbannerstats",
            constraint=models.UniqueConstraint(fields=("period_start", "period_end"), name="unique_period_stats"),
        ),
    ]
