# Generated by Django 4.2.28 on 2026-04-08 04:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0063_marketplaceproduct_is_delivery_free"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0052_alter_cart_options_cart_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewYearSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="e.g., 'New Year Sale 2024'", max_length=255, verbose_name="Sale Name")),
                (
                    "description",
                    models.TextField(blank=True, help_text="Details about the sale", null=True, verbose_name="Description"),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Discount Percentage",
                    ),
                ),
                ("start_date", models.DateTimeField(help_text="When the sale begins", verbose_name="Sale Start Date")),
                ("end_date", models.DateTimeField(help_text="When the sale ends", verbose_name="Sale End Date")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_new_year_sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products participating in this New Year sale",
                        related_name="new_year_sales",
                        to="producer.marketplaceproduct",
                        verbose_name="Products",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Year Sale",
                "verbose_name_plural": "New Year Sales",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["is_active", "start_date", "end_date"], name="market_newy_is_acti_8f49ec_idx"),
                    models.Index(fields=["start_date", "end_date"], name="market_newy_start_d_cb2e87_idx"),
                ],
            },
        ),
    ]
