# Generated by Django 4.2.28 on 2026-10-01 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0064_searchtaxonomynode_searchintentlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0053_newyearsale"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("zone", models.CharField(blank=True, max_length=100)),
                ("expected_delivery_date", models.DateTimeField()),
                ("requirements", models.TextField(blank=True, null=True)),
                ("document", models.FileField(blank=True, null=True, upload_to="", verbose_name="RFQ document")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_request_items",
                        to="producer.marketplaceproduct",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_requests_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
