# Generated by Django 4.2.28 on 2026-10-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='proposed_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
