# Generated by Django 4.2.26 on 2025-11-25 07:46

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0006_delivery_transport_delivery_source_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalBusiness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(max_length=255)),
                ("business_email", models.EmailField(max_length=254, unique=True)),
                ("contact_person", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=20)),
                ("business_address", models.TextField()),
                ("api_key", models.CharField(blank=True, max_length=64, unique=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=64)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("registration_number", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free (100 deliveries/month)"),
                            ("starter", "Starter (500 deliveries/month)"),
                            ("business", "Business (2000 deliveries/month)"),
                            ("enterprise", "Enterprise (Unlimited)"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=60)),
                ("rate_limit_per_hour", models.PositiveIntegerField(default=1000)),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "per_delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_delivery_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000.00"),
                        help_text="Maximum value of delivery allowed",
                        max_digits=10,
                    ),
                ),
                (
                    "allowed_pickup_cities",
                    models.JSONField(default=list, help_text="List of cities where pickup is allowed"),
                ),
                (
                    "allowed_delivery_cities",
                    models.JSONField(default=list, help_text="List of cities where delivery is allowed"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_external_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_external_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "External Business",
                "verbose_name_plural": "External Businesses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "external_delivery_id",
                    models.CharField(help_text="External business's internal delivery ID", max_length=255),
                ),
                ("pickup_name", models.CharField(max_length=255)),
                ("pickup_phone", models.CharField(max_length=20)),
                ("pickup_address", models.TextField()),
                ("pickup_city", models.CharField(max_length=100)),
                ("pickup_latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("pickup_longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("pickup_instructions", models.TextField(blank=True)),
                ("delivery_name", models.CharField(max_length=255)),
                ("delivery_phone", models.CharField(max_length=20)),
                ("delivery_address", models.TextField()),
                ("delivery_city", models.CharField(max_length=100)),
                ("delivery_latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("delivery_longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("delivery_instructions", models.TextField(blank=True)),
                ("package_description", models.TextField()),
                (
                    "package_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in KG",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "package_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Declared value in NPR",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("fragile", models.BooleanField(default=False)),
                ("scheduled_pickup_time", models.DateTimeField(blank=True, help_text="Preferred pickup time", null=True)),
                (
                    "scheduled_delivery_time",
                    models.DateTimeField(blank=True, help_text="Preferred delivery time", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted by Transporter"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed Delivery"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "delivery_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Calculated delivery fee", max_digits=10, null=True
                    ),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Our platform commission", max_digits=10, null=True
                    ),
                ),
                (
                    "transporter_earnings",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Transporter earnings", max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_cod", models.BooleanField(default=False, help_text="Cash on Delivery")),
                (
                    "cod_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "assigned_transporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_external_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "external_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_deliveries",
                        to="external_delivery.externalbusiness",
                    ),
                ),
                (
                    "transport_delivery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_delivery",
                        to="transport.delivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Delivery",
                "verbose_name_plural": "External Deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalDeliveryStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted by Transporter"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted by Transporter"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="external_delivery.externaldelivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Status History",
                "verbose_name_plural": "Delivery Status Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("request_ip", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_size", models.PositiveIntegerField(default=0)),
                ("response_status", models.PositiveIntegerField()),
                ("response_size", models.PositiveIntegerField(default=0)),
                (
                    "response_time",
                    models.DecimalField(decimal_places=3, help_text="Response time in seconds", max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "external_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage_logs",
                        to="external_delivery.externalbusiness",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Usage Log",
                "verbose_name_plural": "API Usage Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("delivery.created", "Delivery Created"),
                            ("delivery.updated", "Delivery Updated"),
                            ("delivery.cancelled", "Delivery Cancelled"),
                            ("delivery.delivered", "Delivery Delivered"),
                            ("delivery.failed", "Delivery Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("webhook_url", models.URLField()),
                ("payload", models.JSONField()),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                (
                    "response_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, help_text="Response time in seconds", max_digits=10, null=True
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_logs",
                        to="external_delivery.externaldelivery",
                    ),
                ),
                (
                    "external_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_logs",
                        to="external_delivery.externalbusiness",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["external_business", "success"], name="external_de_externa_4dad68_idx"),
                    models.Index(fields=["next_retry_at"], name="external_de_next_re_db10fb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimitLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_ip", models.GenericIPAddressField()),
                ("endpoint", models.CharField(max_length=255)),
                ("request_count", models.PositiveIntegerField(default=1)),
                (
                    "time_window",
                    models.CharField(choices=[("minute", "Minute"), ("hour", "Hour")], default="minute", max_length=10),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limit_logs",
                        to="external_delivery.externalbusiness",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Limit Log",
                "verbose_name_plural": "Rate Limit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["external_business", "time_window", "created_at"], name="external_de_externa_acb6a1_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="externaldelivery",
            index=models.Index(fields=["tracking_number"], name="external_de_trackin_32f8ea_idx"),
        ),
        migrations.AddIndex(
            model_name="externaldelivery",
            index=models.Index(fields=["external_business", "status"], name="external_de_externa_4e0245_idx"),
        ),
        migrations.AddIndex(
            model_name="externaldelivery",
            index=models.Index(fields=["status", "created_at"], name="external_de_status_7567f7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="externaldelivery",
            unique_together={("external_business", "external_delivery_id")},
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(fields=["external_business", "created_at"], name="external_de_externa_483dd2_idx"),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(fields=["endpoint", "created_at"], name="external_de_endpoin_1a5a0a_idx"),
        ),
    ]
