# Generated by Django 4.2.26 on 2025-11-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("external_delivery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaldelivery",
            name="transport_delivery",
        ),
    ]
