# Generated by Django 4.2.26 on 2025-11-25 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("external_delivery", "0002_remove_externaldelivery_transport_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalbusiness",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalbusiness",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_business",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
