# Generated by Django 4.2.27 on 2026-01-20 23:49

from decimal import Decimal

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeographicZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., 'Kathmandu City', 'Pokhara Valley'",
                        max_length=255,
                        unique=True,
                        verbose_name="Zone Name",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        help_text="Polygon boundary or center point (WGS 84)",
                        null=True,
                        srid=4326,
                        verbose_name="Geographic Boundary",
                    ),
                ),
                (
                    "center_latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Center Latitude",
                    ),
                ),
                (
                    "center_longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Center Longitude",
                    ),
                ),
                (
                    "radius_km",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Radius in kilometers if using circular zone",
                        null=True,
                        verbose_name="Radius (km)",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("tier1", "Tier 1 (0-5km) - Premium/Same-day"),
                            ("tier2", "Tier 2 (5-25km) - Standard"),
                            ("tier3", "Tier 3 (25-50km) - Economy"),
                            ("tier4", "Tier 4 (50km+) - Remote"),
                        ],
                        db_index=True,
                        help_text="Used for determining delivery costs and times",
                        max_length=20,
                        verbose_name="Delivery Tier",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Shipping Cost",
                    ),
                ),
                ("estimated_delivery_days", models.PositiveIntegerField(default=3, verbose_name="Estimated Delivery Days")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Geographic Zone",
                "verbose_name_plural": "Geographic Zones",
                "ordering": ["tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserLocationSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                ("geo_point", django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name="Geographic Point")),
                (
                    "accuracy_meters",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="GPS Accuracy (meters)"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="For tracking user session",
                        max_length=100,
                        verbose_name="Session ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_snapshots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_snapshots",
                        to="geo.geographiczone",
                        verbose_name="Detected Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Location Snapshot",
                "verbose_name_plural": "User Location Snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleRegion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="e.g., 'Kathmandu Weekend Sale'", max_length=255, verbose_name="Region Name"
                    ),
                ),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only allowed countries/cities can purchase",
                        verbose_name="Is Restricted",
                    ),
                ),
                (
                    "allowed_countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ISO 3166-1 alpha-2 codes: ['NP', 'IN']",
                        verbose_name="Allowed Countries",
                    ),
                ),
                (
                    "allowed_cities",
                    models.JSONField(
                        blank=True, default=list, help_text="List of allowed city names", verbose_name="Allowed Cities"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="geo.geographiczone",
                        verbose_name="Geographic Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Region",
                "verbose_name_plural": "Sale Regions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="geographiczone",
            index=django.contrib.postgres.indexes.GistIndex(fields=["geometry"], name="geo_geograp_geometr_41d053_gist"),
        ),
        migrations.AddIndex(
            model_name="userlocationsnapshot",
            index=django.contrib.postgres.indexes.GistIndex(fields=["geo_point"], name="geo_userloc_geo_poi_45faaf_gist"),
        ),
        migrations.AddIndex(
            model_name="userlocationsnapshot",
            index=models.Index(fields=["user", "-created_at"], name="geo_userloc_user_id_4eb765_idx"),
        ),
    ]
