# Generated by Django 4.2.16 on 2024-10-18 06:31

import uuid

from django.db import migrations


def populate_shop_ids(apps, schema_editor):
    UserProfile = apps.get_model("user", "UserProfile")
    for profile in UserProfile.objects.filter(shop_id__isnull=True):
        profile.shop_id = uuid.uuid4()  # Assign a unique UUID if shop_id is null
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile_shop_id"),
    ]

    operations = [
        migrations.RunPython(populate_shop_ids, reverse_code=migrations.RunPython.noop),
    ]
