# Generated by Django 4.2.16 on 2024-10-18 06:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_populate_shop_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="shop_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
