# Generated by Django 4.2.16 on 2024-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_access_to_marketplace',
            field=models.BooleanField(default=False, verbose_name='Has Access to Marketplace'),
        ),
    ]
