# Generated by Django 4.2.16 on 2024-11-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0022_city_product_location"),
        ("user", "0006_userprofile_has_access_to_marketplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location of the product",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="producer.city",
                verbose_name="Location",
            ),
        ),
    ]
