# Generated by Django 4.2.23 on 2025-07-01 09:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0024_product_avg_daily_demand_product_lead_time_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0008_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="business_type",
            field=models.CharField(
                choices=[("distributor", "Distributor"), ("retailer", "Retailer")],
                default="retailer",
                max_length=12,
                verbose_name="Business Type",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Geo-coordinate: latitude",
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Geo-coordinate: longitude",
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location of the shop",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="producer.city",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="shop_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Shop ID"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
    ]
