# Generated by Django 4.2.23 on 2025-07-11 05:20

import django.db.models.deletion
from django.db import migrations, models

import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_add_role_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                default=user.models.Role.get_default_role,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_profiles",
                to="user.role",
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="shop_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name="Shop ID"),
        ),
    ]
