# Generated by Django 4.2.23 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_userprofile_role_alter_userprofile_shop_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_qr_codes/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payment_qr_payload",
            field=models.TextField(blank=True),
        ),
    ]
