# Generated by Django 4.2.23 on 2025-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_userprofile_payment_qr_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pan_certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload your PAN certificate (PDF, JPG, PNG)",
                null=True,
                upload_to="user_documents/pan_certificates/",
                verbose_name="PAN Certificate",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture (JPG, PNG)",
                null=True,
                upload_to="user_profile_images/",
                verbose_name="Profile Image",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="registration_certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload your business registration certificate (PDF, DOC, DOCX, JPG, PNG)",
                null=True,
                upload_to="user_documents/registration_certificates/",
                verbose_name="Registration Certificate",
            ),
        ),
    ]
