# Generated by Django 4.2.23 on 2025-07-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_userprofile_pan_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registered_business_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Registered Business Name"),
        ),
    ]
