# Generated by Django 4.2.23 on 2025-07-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_userprofile_business_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="business_type",
            field=models.CharField(
                choices=[("distributor", "Distributor"), ("retailer", "Retailer")],
                default="retailer",
                max_length=12,
                verbose_name="Business Type",
            ),
        ),
    ]
