# Generated by Django 4.2.23 on 2025-07-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_userprofile_business_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[("distributor", "Distributor"), ("retailer", "Retailer")],
                max_length=12,
                null=True,
                verbose_name="Business Type",
            ),
        ),
    ]
