# Generated by Django 4.2.24 on 2025-11-02 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0020_userprofile_address_userprofile_bio_userprofile_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("username", models.CharField(blank=True, max_length=150, null=True, verbose_name="Username")),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("login_failed", "Login Failed"),
                            ("account_locked", "Account Locked"),
                            ("ip_blocked", "IP Blocked"),
                        ],
                        default="login_failed",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
                ("user_agent", models.TextField(blank=True, null=True, verbose_name="User Agent")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["ip_address", "timestamp"], name="user_logina_ip_addr_0b938c_idx"),
                    models.Index(fields=["username", "timestamp"], name="user_logina_usernam_7ed925_idx"),
                    models.Index(fields=["user", "timestamp"], name="user_logina_user_id_4ece55_idx"),
                ],
            },
        ),
    ]
