# Generated by Django 4.2.26 on 2025-12-02 07:05

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_loginattempt"),
    ]

    operations = [
        # Add all B2B fields in single SQL operation for speed
        migrations.RunSQL(
            sql="""
                ALTER TABLE user_userprofile 
                ADD COLUMN b2b_verified BOOLEAN DEFAULT FALSE,
                ADD COLUMN credit_limit DECIMAL(12,2) DEFAULT 0,
                ADD COLUMN credit_used DECIMAL(12,2) DEFAULT 0,
                ADD COLUMN payment_terms_days INTEGER DEFAULT 30,
                ADD COLUMN tax_id VARCHAR(50);
                
                -- Set NOT NULL constraints where needed
                UPDATE user_userprofile SET 
                    b2b_verified = FALSE WHERE b2b_verified IS NULL,
                    credit_limit = 0 WHERE credit_limit IS NULL,
                    credit_used = 0 WHERE credit_used IS NULL,
                    payment_terms_days = 30 WHERE payment_terms_days IS NULL;
                
                ALTER TABLE user_userprofile 
                ALTER COLUMN b2b_verified SET NOT NULL,
                ALTER COLUMN credit_limit SET NOT NULL,
                ALTER COLUMN credit_used SET NOT NULL,
                ALTER COLUMN payment_terms_days SET NOT NULL,
                ADD CONSTRAINT chk_credit_limit_positive CHECK (credit_limit >= 0),
                ADD CONSTRAINT chk_credit_used_positive CHECK (credit_used >= 0),
                ADD CONSTRAINT chk_payment_terms_positive CHECK (payment_terms_days > 0);
            """,
            reverse_sql="""
                ALTER TABLE user_userprofile 
                DROP CONSTRAINT IF EXISTS chk_credit_limit_positive,
                DROP CONSTRAINT IF EXISTS chk_credit_used_positive,
                DROP CONSTRAINT IF EXISTS chk_payment_terms_positive,
                DROP COLUMN b2b_verified,
                DROP COLUMN credit_limit,
                DROP COLUMN credit_used,
                DROP COLUMN payment_terms_days,
                DROP COLUMN tax_id;
            """
        ),
    ]
