# Generated by Django 4.2.26 on 2025-12-02 07:05

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_loginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="b2b_verified",
            field=models.BooleanField(
                default=False,
                help_text="Business is verified for B2B purchases with special pricing",
                verbose_name="B2B Verified",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Maximum credit limit allowed for this business",
                max_digits=12,
                verbose_name="Credit Limit",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="credit_used",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Current amount of credit being used",
                max_digits=12,
                verbose_name="Credit Used",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payment_terms_days",
            field=models.PositiveIntegerField(
                default=30, help_text="Number of days allowed for payment (Net terms)", verbose_name="Payment Terms (Days)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="Business tax identification number",
                max_length=50,
                null=True,
                verbose_name="Tax ID/VAT Number",
            ),
        ),
    ]
