# Generated by Django 4.2.27 on 2025-12-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_userprofile_b2b_verified_userprofile_credit_limit_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["business_type", "location"], name="user_userpr_busines_8329a7_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["b2b_verified"], name="user_userpr_b2b_ver_16371d_idx"),
        ),
    ]
