# Generated by Django 4.2.27 on 2026-01-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_userprofile_user_userpr_busines_8329a7_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="recommendation_embedding",
            field=models.JSONField(blank=True, null=True, verbose_name="Recommendation Vector"),
        ),
    ]
