# Generated by Django 4.2.27 on 2026-02-03 11:58

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0024_userprofile_recommendation_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUserProxy",
            fields=[],
            options={
                "verbose_name": "Business User",
                "verbose_name_plural": "Business Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GeneralUserProxy",
            fields=[],
            options={
                "verbose_name": "General User",
                "verbose_name_plural": "General Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
