# Generated by Django 4.2.27 on 2026-01-01 02:38

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryPerformacePopularity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(db_index=True, max_length=500)),
                ("query_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("total_searches", models.BigIntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("unique_sessions", models.IntegerField(default=0)),
                ("searches_today", models.IntegerField(default=0)),
                ("searches_this_week", models.IntegerField(default=0)),
                ("searches_this_month", models.IntegerField(default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                ("total_purchases", models.IntegerField(default=0)),
                ("click_through_rate", models.FloatField(default=0.0)),
                ("conversion_rate", models.FloatField(default=0.0)),
                ("avg_click_position", models.FloatField(default=0.0)),
                ("trending_score", models.FloatField(default=0.0, help_text="Velocity of searches")),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[("up", "Increasing"), ("down", "Decreasing"), ("stable", "Stable"), ("new", "New")],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("primary_category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "detected_categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Categories this query belongs to",
                        size=None,
                    ),
                ),
                ("avg_order_value", models.FloatField(blank=True, null=True)),
                ("revenue_generated", models.FloatField(default=0.0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Query Performance Popularity",
                "verbose_name_plural": "Query Performance Popularities",
                "ordering": ["-total_searches"],
            },
        ),
        migrations.CreateModel(
            name="SearchSuggestionCache",
            fields=[
                ("query_hash", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("suggestions", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("hit_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suggestion Cache",
                "verbose_name_plural": "Suggestion Caches",
            },
        ),
        migrations.CreateModel(
            name="SearchEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("user_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("original_query", models.TextField(verbose_name="Original Query")),
                ("normalized_query", models.CharField(db_index=True, max_length=500)),
                ("query_hash", models.CharField(db_index=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("mobile", "Mobile"), ("desktop", "Desktop"), ("tablet", "Tablet")],
                        default="desktop",
                        max_length=32,
                    ),
                ),
                ("referrer", models.URLField(blank=True, null=True)),
                ("result_count", models.IntegerField(default=0)),
                ("has_click", models.BooleanField(default=False)),
                ("has_purchase", models.BooleanField(default=False)),
                ("click_position", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["normalized_query", "created_at"], name="search_sugg_normali_10a1a8_idx"),
                    models.Index(fields=["session_id", "created_at"], name="search_sugg_session_b0d6fd_idx"),
                    models.Index(fields=["user_id", "created_at"], name="search_sugg_user_id_f93b6e_idx"),
                    models.Index(fields=["has_click", "created_at"], name="search_sugg_has_cli_18a5a6_idx"),
                    models.Index(fields=["has_purchase", "created_at"], name="search_sugg_has_pur_f1af0d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="QueryAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_query", models.CharField(db_index=True, max_length=500)),
                ("source_query_hash", models.CharField(db_index=True, max_length=64)),
                ("target_query", models.CharField(db_index=True, max_length=500)),
                ("target_query_hash", models.CharField(db_index=True, max_length=64)),
                ("co_occurrence_count", models.IntegerField(default=0, help_text="Number of times searched together")),
                ("session_co_occurrence", models.IntegerField(default=0, help_text="Same session occurrences")),
                (
                    "source_to_target_ctr",
                    models.FloatField(
                        default=0.0,
                        help_text="Click-through rate from source to target",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "target_to_source_ctr",
                    models.FloatField(
                        default=0.0,
                        help_text="Click-through rate from target to source",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "conversion_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Purchase rate",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("last_occurrence", models.DateTimeField(auto_now=True)),
                ("decay_score", models.FloatField(default=1.0, help_text="Time-decayed importance")),
                (
                    "association_type",
                    models.CharField(
                        choices=[
                            ("co_search", "Co-Search"),
                            ("category", "Same Category"),
                            ("brand", "Same Brand"),
                            ("complementary", "Complementary"),
                            ("attribute", "Same Attributes"),
                            ("manual", "Manually Added"),
                        ],
                        default="co_search",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Query Association",
                "verbose_name_plural": "Query Associations",
                "indexes": [
                    models.Index(
                        fields=["source_query_hash", "-co_occurrence_count"], name="search_sugg_source__71db64_idx"
                    ),
                    models.Index(
                        fields=["target_query_hash", "-co_occurrence_count"], name="search_sugg_target__0fac28_idx"
                    ),
                    models.Index(fields=["association_type", "-confidence_score"], name="search_sugg_associa_8ed336_idx"),
                    models.Index(fields=["-decay_score"], name="search_sugg_decay_s_061f6b_idx"),
                ],
                "unique_together": {("source_query_hash", "target_query_hash")},
            },
        ),
        migrations.CreateModel(
            name="ManualQueryAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_query", models.CharField(max_length=500)),
                ("target_query", models.CharField(max_length=500)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("synonym", "Synonym"),
                            ("upsell", "Upsell"),
                            ("cross_sell", "Cross-Sell"),
                            ("complementary", "Complementary"),
                            ("alternative", "Alternative"),
                            ("upgrade", "Upgrade"),
                            ("downgrade", "Downgrade"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        default=1.0,
                        help_text="Manual strength score (0-10)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Why this association exists")),
                ("min_price", models.FloatField(blank=True, help_text="Minimum price for this suggestion", null=True)),
                ("max_price", models.FloatField(blank=True, help_text="Maximum price for this suggestion", null=True)),
                (
                    "applicable_categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Categories where this applies",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0, help_text="Higher priority shows first")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Query Association",
                "verbose_name_plural": "Manual Query Associations",
                "unique_together": {("source_query", "target_query")},
            },
        ),
    ]
