# Generated by Django 4.2.23 on 2025-07-25 01:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0025_productview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pickup_address', models.TextField(verbose_name='Pickup Address')),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_contact_name', models.CharField(max_length=255, verbose_name='Pickup Contact Name')),
                ('pickup_contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Pickup Contact Phone')),
                ('delivery_address', models.TextField(verbose_name='Delivery Address')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_contact_name', models.CharField(max_length=255, verbose_name='Delivery Contact Name')),
                ('delivery_contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Delivery Contact Phone')),
                ('package_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=8, verbose_name='Package Weight (kg)')),
                ('package_dimensions', models.CharField(blank=True, help_text='LxWxH in cm', max_length=100, verbose_name='Package Dimensions')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Special Instructions')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned to Transporter'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='available', max_length=20, verbose_name='Delivery Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Delivery Priority')),
                ('requested_pickup_date', models.DateTimeField(verbose_name='Requested Pickup Date')),
                ('requested_delivery_date', models.DateTimeField(verbose_name='Requested Delivery Date')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned At')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Picked Up At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Delivery Fee')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance (km)')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='market.marketplacesale')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='License Number')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Motorcycle/Bike'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('other', 'Other')], max_length=20, verbose_name='Vehicle Type')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('vehicle_capacity', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in kg', max_digits=8, verbose_name='Vehicle Capacity (kg)')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Deliveries')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Average Rating')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total Deliveries')),
                ('successful_deliveries', models.PositiveIntegerField(default=0, verbose_name='Successful Deliveries')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned to Transporter'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='transport.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Tracking',
                'verbose_name_plural': 'Delivery Tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='transport.delivery')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporter')),
            ],
            options={
                'verbose_name': 'Delivery Rating',
                'verbose_name_plural': 'Delivery Ratings',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to='transport.transporter', verbose_name='Assigned Transporter'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['is_verified', 'is_available'], name='transport_t_is_veri_b4bbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['vehicle_type'], name='transport_t_vehicle_6ede0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='transport_t_current_36b359_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryrating',
            unique_together={('delivery', 'rated_by')},
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='transport_d_status_98c6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['transporter', 'status'], name='transport_d_transpo_e4e98d_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['requested_pickup_date'], name='transport_d_request_55c121_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['priority', 'status'], name='transport_d_priorit_3a7c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='transport_d_pickup__1d5d36_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_latitude', 'delivery_longitude'], name='transport_d_deliver_0631a8_idx'),
        ),
    ]
