# Generated by Django 4.2.23 on 2025-07-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporter",
            name="vehicle_documents",
            field=models.FileField(blank=True, null=True, upload_to="vehicle_documents", verbose_name="Vehicle Documents"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="vehicle_image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicle_images", verbose_name="Vehicle Image"),
        ),
    ]
