# Generated by Django 4.2.23 on 2025-07-29 13:38

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transport", "0002_transporter_vehicle_documents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Route Name")),
                ("estimated_distance", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("estimated_duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Delivery Route",
                "verbose_name_plural": "Delivery Routes",
            },
        ),
        migrations.CreateModel(
            name="RouteDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(verbose_name="Delivery Order")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveIndex(
            model_name="transporter",
            name="transport_t_is_veri_b4bbdc_idx",
        ),
        migrations.RemoveField(
            model_name="deliveryrating",
            name="rating",
        ),
        migrations.AddField(
            model_name="delivery",
            name="actual_pickup_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Cancellation Reason"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Cancelled At"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_attempts",
            field=models.PositiveIntegerField(default=0, verbose_name="Delivery Attempts"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_instructions",
            field=models.TextField(blank=True, verbose_name="Delivery Instructions"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_notes",
            field=models.TextField(blank=True, verbose_name="Delivery Notes"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_photo",
            field=models.ImageField(blank=True, null=True, upload_to="delivery_proofs", verbose_name="Delivery Photo"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="fragile",
            field=models.BooleanField(default=False, verbose_name="Fragile Package"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="fuel_surcharge",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name="Fuel Surcharge"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="max_delivery_attempts",
            field=models.PositiveIntegerField(default=3, verbose_name="Max Delivery Attempts"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="package_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Package Value"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="pickup_instructions",
            field=models.TextField(blank=True, verbose_name="Pickup Instructions"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="requires_signature",
            field=models.BooleanField(default=False, verbose_name="Requires Signature"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="delivery_signatures", verbose_name="Signature"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="deliveryrating",
            name="communication_rating",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="Communication (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrating",
            name="is_anonymous",
            field=models.BooleanField(default=False, verbose_name="Anonymous Rating"),
        ),
        migrations.AddField(
            model_name="deliveryrating",
            name="overall_rating",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="Overall Rating (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrating",
            name="package_handling_rating",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="Package Handling (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrating",
            name="punctuality_rating",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="Punctuality (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Business Name"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="cancelled_deliveries",
            field=models.PositiveIntegerField(default=0, verbose_name="Cancelled Deliveries"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="Commission Rate (%)",
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="earnings_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Total Earnings"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="emergency_contact",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, verbose_name="Emergency Contact"
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="insurance_expiry",
            field=models.DateField(blank=True, null=True, verbose_name="Insurance Expiry Date"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transporter",
            name="license_expiry",
            field=models.DateField(blank=True, null=True, verbose_name="License Expiry Date"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="service_radius",
            field=models.PositiveIntegerField(default=50, verbose_name="Service Radius (km)"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive"), ("suspended", "Suspended"), ("offline", "Offline")],
                default="active",
                max_length=20,
                verbose_name="Transporter Status",
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Tax ID"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="verification_documents",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="package_weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Weight in kg",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Package Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                    ("same_day", "Same Day"),
                ],
                default="normal",
                max_length=15,
                verbose_name="Delivery Priority",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("assigned", "Assigned to Transporter"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                    ("failed", "Failed Delivery"),
                ],
                default="available",
                max_length=20,
                verbose_name="Delivery Status",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrating",
            name="transporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="transport.transporter"
            ),
        ),
        migrations.AlterField(
            model_name="deliverytracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("assigned", "Assigned to Transporter"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                    ("failed", "Failed Delivery"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="vehicle_capacity",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Maximum weight capacity in kg",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Vehicle Capacity (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("bike", "Motorcycle/Bike"),
                    ("car", "Car"),
                    ("van", "Van"),
                    ("truck", "Truck"),
                    ("bicycle", "Bicycle"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Vehicle Type",
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["tracking_number"], name="transport_d_trackin_d2f6b2_idx"),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["created_at"], name="transport_d_created_42fc66_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryrating",
            index=models.Index(fields=["transporter", "overall_rating"], name="transport_d_transpo_14c37e_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryrating",
            index=models.Index(fields=["created_at"], name="transport_d_created_4695bb_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverytracking",
            index=models.Index(fields=["delivery", "timestamp"], name="transport_d_deliver_dda54d_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverytracking",
            index=models.Index(fields=["status"], name="transport_d_status_7b42bf_idx"),
        ),
        migrations.AddIndex(
            model_name="transporter",
            index=models.Index(fields=["is_verified", "is_available", "status"], name="transport_t_is_veri_9bc15a_idx"),
        ),
        migrations.AddIndex(
            model_name="transporter",
            index=models.Index(fields=["status"], name="transport_t_status_88c84d_idx"),
        ),
        migrations.AddIndex(
            model_name="transporter",
            index=models.Index(fields=["service_radius"], name="transport_t_service_d0e371_idx"),
        ),
        migrations.AddField(
            model_name="routedelivery",
            name="delivery",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="transport.delivery"),
        ),
        migrations.AddField(
            model_name="routedelivery",
            name="route",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="transport.deliveryroute"),
        ),
        migrations.AddField(
            model_name="deliveryroute",
            name="deliveries",
            field=models.ManyToManyField(through="transport.RouteDelivery", to="transport.delivery"),
        ),
        migrations.AddField(
            model_name="deliveryroute",
            name="transporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="routes", to="transport.transporter"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routedelivery",
            unique_together={("route", "delivery")},
        ),
    ]
