# Generated by Django 4.2.23 on 2025-08-05 04:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transport", "0003_deliveryroute_routedelivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransporterDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("driving_license", "Driving License"),
                            ("vehicle_registration", "Vehicle Registration"),
                            ("vehicle_insurance", "Vehicle Insurance"),
                            ("id_proof", "ID Proof"),
                            ("address_proof", "Address Proof"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Document Type",
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=100, null=True, verbose_name="Document Number")),
                (
                    "document_file",
                    models.FileField(
                        upload_to="transporter_documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"],
                                message="Only PDF, JPG, and PNG files are allowed.",
                            )
                        ],
                        verbose_name="Document File",
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True, verbose_name="Issue Date")),
                ("expiry_date", models.DateField(blank=True, null=True, verbose_name="Expiry Date")),
                ("is_verified", models.BooleanField(default=False, verbose_name="Is Verified")),
                ("verified_at", models.DateTimeField(blank=True, null=True, verbose_name="Verified At")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Verification Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="transport.transporter",
                        verbose_name="Transporter",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transporter Document",
                "verbose_name_plural": "Transporter Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
