# Generated by Django 4.2.26 on 2025-11-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producer", "0046_marketplaceproduct_is_made_in_nepal"),
        ("market", "0032_alter_delivery_options_delivery_actual_delivery_date_and_more"),
        ("transport", "0004_transporterdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="sale",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_delivery",
                to="producer.sale",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="marketplace_sale",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_details",
                to="market.marketplacesale",
            ),
        ),
    ]
