# Generated by Django 4.2.26 on 2025-11-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0005_delivery_sale_alter_delivery_marketplace_sale"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="delivery",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("marketplace_sale__isnull", False), ("sale__isnull", True)),
                    models.Q(("marketplace_sale__isnull", True), ("sale__isnull", False)),
                    _connector="OR",
                ),
                name="transport_delivery_source_constraint",
            ),
        ),
    ]
