# Generated by Django 4.2.26 on 2025-11-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_delivery", "0002_remove_externaldelivery_transport_delivery"),
        ("transport", "0006_delivery_transport_delivery_source_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="external_delivery",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_transport_delivery",
                to="external_delivery.externaldelivery",
            ),
        ),
    ]
