# Generated by Django 4.2.26 on 2025-11-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0007_delivery_external_delivery"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="delivery",
            name="transport_delivery_source_constraint",
        ),
        migrations.AddConstraint(
            model_name="delivery",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("external_delivery__isnull", True), ("marketplace_sale__isnull", False), ("sale__isnull", True)
                    ),
                    models.Q(
                        ("external_delivery__isnull", True), ("marketplace_sale__isnull", True), ("sale__isnull", False)
                    ),
                    models.Q(
                        ("external_delivery__isnull", False), ("marketplace_sale__isnull", True), ("sale__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="transport_delivery_source_constraint",
            ),
        ),
    ]
