# Generated by Django 4.2.27 on 2025-12-25 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Profile Viewed"),
                            ("contact", "Contact Initiated"),
                            ("order", "Order Placed"),
                            ("connect", "Connection Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["business", "target_business"], name="recommendat_busines_494a92_idx"),
                    models.Index(fields=["target_business", "interaction_type"], name="recommendat_target__bab759_idx"),
                ],
                "unique_together": {("business", "target_business", "interaction_type")},
            },
        ),
    ]
